### ISSUE TITLE
Bug do Softban não estar desbanindo o usuário (nesse servidor)

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1008]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/9393424e6e65b2a5b4e338dd74dd3fc0.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-573286829932019757`**

<hr>

**Bug do Softban não estar desbanindo o usuário (nesse servidor):**

As punições do servidor gringo são sincronizadas aqui e virse e versa, então a Lori bane aqui, desbane no mesmo momento, porém ela bane novamente por causa da sincronização do servidor gringo. Só conferir o audit-log

**Comment by MrPowerGamerBR** [comment]
Tão antigo que nem é mais relevante
