### ISSUE TITLE
Desvendando Séculos
+sec {número romano}
EX

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1038]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/48cc7d1413d762f28888c8e585e26501.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-575806372810326036`**

<hr>

**Desvendando Séculos**
+sec {número romano}
EX: +sec XVI a.C.
+sec XXV

Eu não sei contar números romanos ,_,

**Comment by Nightdavisao** [comment]
Google e escola estão aí pra isso
