### ISSUE TITLE
com sonhos podia comprar "vips" aq no servidor da lori <3

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1050]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/403956886543663104/1c9b19e83c39db0461b2bcc9be65928d.png">

**Sugestão de `Sr.yNerd#3195` (`403956886543663104`)**
**ID da Mensagem: `359139508681310212-575474649132040213`**

<hr>

com sonhos podia comprar "vips" aq no servidor da lori <3

**Comment by MrPowerGamerBR** [comment]
Quando tiver o sistema de economia local (que será possível migrar sonhos -> economia local), talvez eu faça isso
