### ISSUE TITLE
Fazer a loritta poder dar cargos nos servidores ao chegar em um level espe...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1059]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/330512765078732801/39b5b461a8066bcc279dfb9b524bd397.png">

**Sugestão de `🎶🎧Otaku Gamer🎧🎶#1373` (`330512765078732801`)**
**ID da Mensagem: `359139508681310212-577003153690722304`**

<hr>

Fazer a loritta poder dar cargos nos servidores ao chegar em um level específico no servidor colocando a função no painel do bot no site pra a gente poder escolher o level que tal cargo será dado

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
