### ISSUE TITLE
Fazer a loritta poder dar cargos nos servidores ao chegar em um level espe...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1096]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/395592015611428864/6377b897e1436cc9043ea8d22b893c87.png">

**Sugestão de `LucasGamer02#6718` (`395592015611428864`)**
**ID da Mensagem: `359139508681310212-579701726026661908`**

<hr>

Fazer a loritta poder dar cargos nos servidores ao chegar em um level específico no servidor, ai o usuario vai interagindo exemplo: Reagindo as mensagens, Conversando e etc para subir de level

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
