### ISSUE TITLE
Adicionar algum comando pra ver as estatísticas de um jogador de Fortnite ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1106]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/226476434367971332/b55d20fabc5d4fe2eb9c8a702526553c.png">

**Sugestão de `Choose#7734` (`226476434367971332`)**
**ID da Mensagem: `359139508681310212-579469903522824214`**

<hr>

Adicionar algum comando pra ver as estatísticas de um jogador de Fortnite 👍 tem muito servidor que usa lori focado em fortnite, isso seria bom

**Comment by MrPowerGamerBR** [comment]
Adicionado em https://github.com/LorittaBot/Loritta/commit/229502d11a60c0d328ee5db1885a1665dfadf4ba
