### ISSUE TITLE
Criar um fórum pra Loritta, pra mandar embeds prontos, postar comados feit...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1111]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/361977144445763585/d154795a97bbc9c9d74ab9e0e38902e6.png">

**Sugestão de `PeterStark000#6011` (`361977144445763585`)**
**ID da Mensagem: `359139508681310212-580793343642959908`**

<hr>

Criar um fórum pra Loritta, pra mandar embeds prontos, postar comados feitos, e ter como ajudar pessoas com dúvidas em comandos, embeds e outras coisas....

**Comment by zKeevyn** [comment]
Apoio
