### ISSUE TITLE
Fazer um sitema de nivel semelhante ao mee6 em que quanto mais a pessoa co...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1136]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/511642593721974794/cba1b05277b92207162fd45bbccf8650.png">

**Sugestão de `Pão_torrado#0777` (`511642593721974794`)**
**ID da Mensagem: `359139508681310212-582397226974707713`**

<hr>

Fazer um sitema de nivel semelhante ao mee6 em que quanto mais a pessoa conversa mais XP ela ganha, assim subindo de nivel e ganhando cargos que a gente colocar

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
