### ISSUE TITLE
Caso uma imagem estiver anexada na hora de realizar uma punição, ela vira ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1171]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/392a4962e3d810db8eef4a2ea93a0504.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-583313307411283968`**

<hr>

Caso uma imagem estiver anexada na hora de realizar uma punição, ela vira um hyper link na razão da embed

**Comment by MrPowerGamerBR** [comment]
Duplicata de https://github.com/LorittaBot/Loritta/issues/1169
