### ISSUE TITLE
tirar a taxa do +pay ;w; tu n pode mais doar 1 sonho ou 0,5 e tals e isso ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1188]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/273957582224228353/d7227b06e40b149194556966e95969d8.png">

**Sugestão de `'•̶๖̶̶̶ۣۣۜۜ͜MαяҡiS◕ω◕#1635` (`273957582224228353`)**
**ID da Mensagem: `359139508681310212-584908834678505479`**

<hr>

tirar a taxa do +pay ;w; tu n pode mais doar 1 sonho ou 0,5 e tals e isso é ruim,  alem do mais imposto é roubo >:(

**Comment by MrPowerGamerBR** [comment]
¯\_(ツ)_/¯
