### ISSUE TITLE
Concertar isso

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1200]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/300323442715262976/393519f22550dd179b32cb4004eccd44.png">

**Sugestão de `ƐƖǝɹods [̲̅B̲̅][̲̅O̲̅][̲̅T̲̅]#1028` (`300323442715262976`)**
**ID da Mensagem: `359139508681310212-585160741053792256`**

<hr>

Concertar isso

![https://cdn.discordapp.com/attachments/359139508681310212/585160729376587778/Screenshot_20190603-183557_1.jpg](https://cdn.discordapp.com/attachments/359139508681310212/585160729376587778/Screenshot_20190603-183557_1.jpg)

**Comment by MrPowerGamerBR** [comment]
Já foi consertado
