### ISSUE TITLE
+limpar suportar mais de 100 mensagens. O comando entraria em looping e ap...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1207]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/a_7f1d9e9f0ef6c80f7b55602344805b90.gif">

**Sugestão de `Yuri.#0005` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-584405160453865473`**

<hr>

`+limpar` suportar mais de 100 mensagens. O comando entraria em looping e apagaria 100 mensagens por vez. (Para evitar rate limit a ação iria ter um delay)

**Comment by Nightdavisao** [comment]
Isso seria muito lento então nah

**Comment by OswaldoDayJr** [comment]
O Dyno faz isso é já é uma prova que funciona bem
