### ISSUE TITLE
Leveled Role ( cargo a certo nivel/ opcional ) 

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1227]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/542823897301778497/77bf0a3cd45f13b8218d99a86a6d388c.png">

**Sugestão de `👌Comander👌#9785` (`542823897301778497`)**
**ID da Mensagem: `359139508681310212-586708790095773706`**

<hr>

Leveled Role ( cargo a certo nivel/ opcional ) :  Caso o player chegar num certo nivel, ele ganha algum cargo (Exemplo: Chegar a level 1: Iniciante, Chegar a level 5: Mediario)

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
