### ISSUE TITLE
Debaixo do autorole, terá uma pastinha chamado Leveled role, quando entrar...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1234]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/542823897301778497/e7ead368b1eed0f6a0f5a94e6b345eeb.png">

**Sugestão de `👌Comander👌#9785` (`542823897301778497`)**
**ID da Mensagem: `359139508681310212-586710817702150182`**

<hr>

Debaixo do autorole, terá uma pastinha chamado Leveled role, quando entrar lá,téra uma listinha dos cargos dos servers, e voce poderá digitar qual o numero(que vai ser considerado level) e depois qual o cargo, Assim salvando

![https://cdn.discordapp.com/attachments/359139508681310212/586710814279598095/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/586710814279598095/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
