### ISSUE TITLE
Sugestão para quem é memeiro

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1258]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/260582365171154944/27f53a3074d4f990bdf347a48d1d390b.png">

**Sugestão de `PotatoX_Xotatop#5823` (`260582365171154944`)**
**ID da Mensagem: `359139508681310212-588180688449175584`**

<hr>

Sugestão para quem é memeiro
--------------------------------------------------
(((A IMAGEM TEM QUE VIR PNG)))
Um comando chamado ``+SeloAntiKibe (Imagem) (Texto1) (Texto2) `` 
Caso não colocar a imagem. vai ficar só as letras sem fundo
Exemplo: +SeloAntiKibe (Imagem de galaxia) (South America Memes) (Cópia não comedia)
Resultado:
Ps: A imagem é só um selo que tu faz. não é que nem o ``+sam``

![https://cdn.discordapp.com/attachments/359139508681310212/588180684301139968/Z.png](https://cdn.discordapp.com/attachments/359139508681310212/588180684301139968/Z.png)

**Comment by riquelmelopess** [comment]
+sam

> +Sam
