### ISSUE TITLE
A Loritta não tá pegando com servericon o gif do servidor quando ele tem N...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1284]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/361977144445763585/841122c779cf1faed56df6b3a6145e91.png">

**Sugestão de `PeterStark000#6011` (`361977144445763585`)**
**ID da Mensagem: `359139508681310212-589487593708716053`**

<hr>

A Loritta não tá pegando com ``servericon`` o gif do servidor quando ele tem Nitro Boosting..

**Comment by MrPowerGamerBR** [comment]
Precisa esperar o JDA atualizar para poder implementar isto.
