### ISSUE TITLE
o +say suportar caixas
desse jeito

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1288]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/431071633206411294/a6f121ac91681d9ae827b1d1d7cfd29d.png">

**Sugestão de `ABBA#2371` (`431071633206411294`)**
**ID da Mensagem: `359139508681310212-589576720823091200`**

<hr>

o +say suportar `caixas`
```desse jeito```

**Comment by MrPowerGamerBR** [comment]
O `+say` não suporta code blocks para evitar usarem "` @menção`", mas dá para bypassear usando `rawArgs` em vez de `args`

**Comment by MrPowerGamerBR** [comment]
Duplicata de https://github.com/LorittaBot/Loritta/issues/1274
