### ISSUE TITLE
a opção de desativar emojis do seu servidor no +findemoji pq to cansado de...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1334]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/273957582224228353/d7227b06e40b149194556966e95969d8.png">

**Sugestão de `'•̶๖̶̶̶ۣۣۜۜ͜MαяҡiS◕ω◕#1635` (`273957582224228353`)**
**ID da Mensagem: `359139508681310212-592923263970181137`**

<hr>

a opção de desativar emojis do seu servidor no +findemoji pq to cansado de ve gente roubando emojis q eu fiz ;w;

**Comment by Kikoszzz** [comment]
Já está disponível?
