### ISSUE TITLE
Problema com os +contribuidores

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1367]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/144943581965189120/5b23bd2be0ea2713b8c5d988203ddfe2.png">

**Sugestão de `SMGLinuxL2G#8818` (`144943581965189120`)**
**ID da Mensagem: `359139508681310212-597546096667131904`**

<hr>

Problema com os +contribuidores

![https://cdn.discordapp.com/attachments/359139508681310212/597546094808793089/Screenshot_20190707-225318.png](https://cdn.discordapp.com/attachments/359139508681310212/597546094808793089/Screenshot_20190707-225318.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
