### ISSUE TITLE
No site da Lori, ter como se fosse um Registro de Auditoria, para informar...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1369]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/487998225173839902/a_4611f2099dd8e1fbcc0439f7debf9514.gif">

**Sugestão de `Donald#0002` (`487998225173839902`)**
**ID da Mensagem: `359139508681310212-597830067078299658`**

<hr>

No site da Lori, ter como se fosse um Registro de Auditoria, para informar que fez alterações em alguma coisa, alguns servers estão passando por problemas com staffers mechendo nas configurações colocando pra membros novos receberem cargo de Owner e etc

**Comment by MrPowerGamerBR** [comment]
Já foi adicionado
