### ISSUE TITLE
Emoji Mashup

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1428]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/107279862934331392/860865b28ba22dff082c9a73aca8b573.png">

**Sugestão de `SenhorMicha#2476` (`107279862934331392`)**
**ID da Mensagem: `359139508681310212-603126249933504532`**

<hr>

**Emoji Mashup**

Recentemente, tá bombando no Twitter um perfil que mescla (mistura) emojis, formando combinações interessantes e até inusitados de emoji. A minha ideia é que se fosse viável, fizesse um comando para mesclar (misturar) emojis. ```+emojimashup```

Exemplo na imagem.

_Para entender o funcionamento, olhe o perfil `@Emo#7983` (`380155502283456512`)jiMashupBot no Twitter._

![https://cdn.discordapp.com/attachments/359139508681310212/603126242740535306/image0.jpg](https://cdn.discordapp.com/attachments/359139508681310212/603126242740535306/image0.jpg)

**Comment by MrPowerGamerBR** [comment]
Já implementado
