### ISSUE TITLE
Mudar o +help da @Loritta Morenitta 😘 em vez de mandar uma mensagem com v...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1466]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/404984539799093258/a_f4a618358c5a3ae4ad27caf0a50f206b.gif">

**Sugestão de `Gaster | ᴼᴮᵀ#0001` (`404984539799093258`)**
**ID da Mensagem: `359139508681310212-610232910204895242`**

<hr>

Mudar o +help da <@!297153970613387264> em vez de mandar uma mensagem com varias reações podia mandar um link do website da <@!297153970613387264> mostrando todos os comandos separados por categorias.

**Comment by MrPowerGamerBR** [comment]
Eu não irei remover tudo da `+ajuda`, mas irei colocar um link para ver os comandos no website.
