### ISSUE TITLE
Cargos Por Level.

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1481]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/566026152188313600/b496531e6bdb7440b65c9b5463557a32.png">

**Sugestão de `Fábio 🍃#9007` (`566026152188313600`)**
**ID da Mensagem: `359139508681310212-609402163927580688`**

<hr>

Cargos Por Level.

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
