### ISSUE TITLE
Mais opções do que fazer com os sonhos, jogos que faça perder ou ganhar so...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1485]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/508673053333651460/a_95fd4cdad388fe94ee04ea93eae0ba5b.gif">

**Sugestão de `MF   SAGAZLX.ᵈᵃ ᵏᵃᵘᵃⁿʸ💕#1999` (`508673053333651460`)**
**ID da Mensagem: `359139508681310212-612894752836157460`**

<hr>

Mais opções do que fazer com os sonhos, jogos que faça perder ou ganhar sonhos.

**Comment by MrPowerGamerBR** [comment]
Suporte a transferência de sonhos SparklyPower <-> Loritta será implementado em breve
