### ISSUE TITLE
não sei se bugou só no meu, mas mandei mesmo assim 👍

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1538]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/376891945609461770/54bc6931b436e222dbe8da3003d8f252.png">

**Sugestão de `Joaogador#7573` (`376891945609461770`)**
**ID da Mensagem: `359139508681310212-617550799060598785`**

<hr>

não sei se bugou só no meu, mas mandei mesmo assim 👍

![https://cdn.discordapp.com/attachments/359139508681310212/617550791477035065/IMG_20190831_234506.jpg](https://cdn.discordapp.com/attachments/359139508681310212/617550791477035065/IMG_20190831_234506.jpg)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
