### ISSUE TITLE
Pequenas mudanças no contador de membro #02

### ISSUE THREAD

**Issue by zYuri23** [LorittaBot/Loritta#160]
Adicionar a opção de mudar a cor de seu contador, como deixar os emojis vermelho, azul 

Ou...
até a opção de um "Rainbowmode" onde a cor deles iriam se aleatorizar a cada chegada/saída de um membro

**Comment by MrPowerGamerBR** [comment]
Implementado parcialmente em https://github.com/LorittaBot/Loritta/pull/193
