### ISSUE TITLE
Ter como fazer a loritta lembrar de tal coisa todos os dias no +lembrete

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1665]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/494795833351602176/c46bc593b173b2a18413db9adc145012.png">

**Sugestão de `SrGatinho#6356` (`494795833351602176`)**
**ID da Mensagem: `359139508681310212-628887252038320129`**

<hr>

Ter como fazer a loritta lembrar de tal coisa todos os dias no +lembrete
tipo um loop ai para a pessoa ser lembrada todos os dias a loritta pode perguntar se ela deseja ser lembrada todos os dias a cada tal hora e se ela não quiser mais ela pode cancelar no +lembrete list

**Comment by vsmesquita** [comment]
acc
