### ISSUE TITLE
Auto-role de level up por conversar nos chats

### ISSUE THREAD

**Issue by diegofelipem** [LorittaBot/Loritta#174]
Sugiro que o sistema de auto-role da loritta, alem de dar um cargo inicial ao usuário quando entra no server, também tivesse um sistema de auto-role por level up, assim, quando o usuário atingisse determinado nivek no rank por conversar nos chats, poderia ir ganhando novos cargos.  Ex.:

No server onde sou adm, os cargos de level up sao dados quando o usuario atinge o nivel 1, 5, 10, 20, 30 e 40., mas por outro bot. Mas gostaria de deixar essa função a cargo da loritta, por ser um bot mais personalizável e amigavel de se configurar.

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
