### ISSUE TITLE
resolver o bug dos emojis não aparecer

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1768]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/485141005796900867/282de51a145b724d4013735d0381c087.png">

**Sugestão de `!                    panda pedro#7461` (`485141005796900867`)**
**ID da Mensagem: `359139508681310212-640173214613635072`**

<hr>

resolver o bug dos emojis não aparecer

![https://cdn.discordapp.com/attachments/359139508681310212/640173208632426496/Capturar.PNG](https://cdn.discordapp.com/attachments/359139508681310212/640173208632426496/Capturar.PNG)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido faz teeeeempo
