### ISSUE TITLE
Adicionar uma forma de resetar o rank de xp da Loritta

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1771]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/570392186227785778/beefb5084dda8342932af7a9b5e842e2.png">

**Sugestão de `Daxner#1732` (`570392186227785778`)**
**ID da Mensagem: `359139508681310212-641057837186940964`**

<hr>

Adicionar uma forma de resetar o rank de xp da Loritta

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
