### ISSUE TITLE
Melhorar o modo escuro, hehe. Ele tá meio bugado.

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1781]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/527598557839228930/c5bf381fcefdc0655b8601c08ce0d525.png">

**Sugestão de `Misael234#3039` (`527598557839228930`)**
**ID da Mensagem: `359139508681310212-642727811693412382`**

<hr>

Melhorar o modo escuro, hehe. Ele tá meio bugado.

![https://cdn.discordapp.com/attachments/359139508681310212/642727803795800093/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/642727803795800093/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
