### ISSUE TITLE
Pelo o que eu vi, nesta linha dá uma exception bem chatinha... daí quando executa o +ligar a Lori manda mensagem de erro.

### ISSUE THREAD

**Issue by MrGaabriel** [LorittaBot/Loritta#18]
https://github.com/LorittaBot/Loritta/blob/660d2c0d478a6a76d9745388e95843e45a7c7943/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/LigarCommand.kt#L33

**Comment by MrPowerGamerBR** [comment]
Nem eu sei porque isto estava acontecendo, mas agora não está mais acontecendo, então... 🤷

Provavelmente foi por causa do JRebel ao dar reload.
