### ISSUE TITLE
+embed <mensagem> envia diretamente uma mensagem em embed

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1832]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/586164335592865792/3cb64533b9d02d6db4c7248cbcf80764.png">

**Sugestão de `FBRRafa#9650` (`586164335592865792`)**
**ID da Mensagem: `359139508681310212-648957967659433984`**

<hr>

```+embed <mensagem>``` envia diretamente uma mensagem em embed

**Comment by MrPowerGamerBR** [comment]
O `+say` já permite enviar embeds
