### ISSUE TITLE
class CoringaCommand 

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1852]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/351760430991147010/98ea5f5e2f4de51aec474711d803fed5.png">

**Sugestão de `Arth#4269` (`351760430991147010`)**
**ID da Mensagem: `359139508681310212-650819171621273640`**

<hr>

```class CoringaCommand : BasicSkewedImageCommand(
		arrayOf("coringa", "joker"),
 		CommandCategory.IMAGES,
 		"commands.images.coringa.description",
 		"coringa.png",
 		Corners(
 				255.74295043945312f, 196.27969360351562f,
 				399.2554931640625f, 206.9936065673828f,
 				388.00860595703125f, 304.5141906738281f,
 				251.88442993164062f, 294.34588623046875f 		) 
)
 ```

![https://cdn.discordapp.com/attachments/359139508681310212/650819165413834773/1575232961462.png](https://cdn.discordapp.com/attachments/359139508681310212/650819165413834773/1575232961462.png)

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/commit/a07278a31a210d8eb902f83066e1c735517156f3
