### ISSUE TITLE
Raid e Spam no bloqueador de convites

### ISSUE THREAD

**Issue by zYuri23** [LorittaBot/Loritta#186]
Após uma raid muito grande acontecer, a Lori parece que não consegue processar todos os convites bloqueados e começa a spammar sem fim, Quando isso acontecesse a Lori deveria verificar os convites e enviar apenas poucos, ou até mesmo um para evitar todo o spam e fazer a Raid falhar.

**Comment by MrPowerGamerBR** [comment]
@MrGaabriel para evitar isto, daria para criar um cache de convites já verificados e automaticamente deletar tais convites em vez de ficar usando a API do Discord toda hora.

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/commit/18d34eebd957f3774150f3ec12e0dbb8596c671f isto irá fazer que a Lori faça cache dos invites verificados, ela ainda irá continuar a fazer "spam" toda hora que enviarem um convite, mas pelo ou menos irá deletar os convites mais rapidamente.
