### ISSUE TITLE
Arrumar o BUG de que a Loritta não apaga o convite quando escreve o convit...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#1911]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/328973123351216130/a_86cb7e0b8537a361fb7d9e8eabe0dfe2.gif">

**Sugestão de `LuizF.#0001` (`328973123351216130`)**
**ID da Mensagem: `359139508681310212-656644788434632723`**

<hr>

Arrumar o BUG de que a Loritta não apaga o convite quando escreve o convite com letra maiúscula.

![https://cdn.discordapp.com/attachments/359139508681310212/656644781342064661/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/656644781342064661/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
