### ISSUE TITLE
Suporte a twitch

### ISSUE THREAD

**Issue by Maycoooonm** [LorittaBot/Loritta#2]
Acho que seria legal se a loritta avisa-se quanto um canal especifico esta em live.

**Comment by MrPowerGamerBR** [comment]
Vou tentar fazer isto depois

**Comment by MrPowerGamerBR** [comment]
Não, eu não esqueci dessa sugestão, eu ainda não fiz ela porque eu ainda preciso ver como a API do Twitch funciona. (e porque normalmente eu faço primeiro as coisas que eu acho interessantes e legais, como eu não acompanho ninguém no Twitch... 🤷‍♀️)
