### ISSUE TITLE
Comando para jogar jogo-da-velha pelo próprio Discord

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#2065]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/468935610053427235/fa556319af57498b6202417b968f2ee6.png">

**Sugestão de `iiAmDoggin#1894` (`468935610053427235`)**
**ID da Mensagem: `359139508681310212-673958445761953825`**

<hr>

Comando para jogar jogo-da-velha pelo próprio Discord

**Comment by tiagoformentini** [comment]
Boa noite. Procurando um jeito de desativar os 2 jogos (jogo da velha e reversi)  do chat spark, será que alguém pode me ajudar ?
