### ISSUE TITLE
Change "+background" message to be nicer

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2098]
We don't need to tell that the old feature was removed anymore, we also should point users to the daily shop.

https://loritta.website/user/@me/dashboard/backgrounds

https://loritta.website/user/@me/dashboard/daily-shop

**Comment by joaoesteves10** [comment]
fixed [here](https://github.com/LorittaBot/Loritta/commit/3861b843d1aa16d3b59ba9587fd44e3df7c6b13c)
