### ISSUE TITLE
Add a feature to remove warns by the warn ID

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2111]
In the `+warnlist`, each warn would have its own ID.

Moderators would be able to remove warns by using `+unwarn User WarnID`

https://canary.discordapp.com/channels/297732013006389252/359139508681310212/710714596511449100

**Comment by jaxxibae** [comment]
I'll try to do this, but there are some questions that should be made:
1. How are IDs attributed? Should we use incremental counting (1, 2, 3...)?
2. How will it work for (all current) non-ID warns? Order them from oldest to newest and attribute a number to them?
3. Should incremental counting be used, will it be on a user-to-user basis? (say, there are two users, X and Y, and both have two warns. Will both warns have distinct numbers (user X has warns 1 and 2, user Y has warns 3 and 4) or the same number for both (user X and user Y both have warns 1 and 2)?)

**Comment by MrPowerGamerBR** [comment]
1. Incremental counting from the oldest warn for the user being seen in the `+warnlist` to the newest warn.

This means that if I warned two different users, both warn IDs for the `+unwarn` command would be `1`.

2. Look above

3. Incremental

We could use the database warn ID but that's kinda lame due to:
![image](https://user-images.githubusercontent.com/9496359/82074264-e47c8e00-96b0-11ea-95e5-fde07768fdeb.png)

**Comment by jaxxibae** [comment]
Looks good, will start doing the dirty stuff!
