### ISSUE TITLE
Hardcoded strings that needs to be migrated to the locale files

### ISSUE THREAD

**Issue by jaxxibae** [LorittaBot/Loritta#2119]
Some strings appear to be hardcoded, and that makes it difficult for strings to be translated to other languages.

* [x] [Avisado](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnListCommand.kt#L85)
* [x] [Lista de Avisos](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnListCommand.kt#L67)
* [ ] [Premium Features Web Page](https://github.com/LorittaBot/Loritta/blob/development/loritta-website/spicy-morenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/routes/DonateRoute.kt#L38)

(there are WAY more strings than these two, checking every file would be tedious to see, will make a list later)

**Comment by bit-man** [comment]
I would like to attack this bug but no idea where to start. Any pointers on the localization mechanism?

**Comment by SrGaabriel** [comment]
@bit-man You can search for the locales at the repository (https://github.com/LorittaBot/LorittaLocales) or at crowdin (https://crowdin.loritta.website).

An example of locale migration can be found here: https://github.com/LorittaBot/Loritta/pull/2218
