### ISSUE TITLE
Download link in "+botinfo extended" is wrong if the build was compiled via GitHub

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2130]
The "+botinfo extended" always show the PerfectDreams' Jenkins server. However sometimes we may use GitHub's builds.

Maybe it would be nice to pass an attribute to Gradle that says from where the build is being run (Jenkins or GitHub) and show the correct link

**Comment by bit-man** [comment]
I'll try to fix this bug

**Comment by MrPowerGamerBR** [comment]
It is possible to fix it by replacing the URL with `https://github.com/LorittaBot/Loritta/actions/runs/{BuildId}`, however the Build ID is *not* saved in the Manifest file yet, so you would need to add that to the manifest (editing the `.github/workflows/*.yml` files to pass the Build ID, then editing `build.gradle.kts` to include the System Property into the build) and then get the Build ID to display on the URL
