### ISSUE TITLE
Imagem/GIF upada no Embed da Punição

### ISSUE THREAD

**Issue by Redig19** [LorittaBot/Loritta#215]
Quando a pessoa for usar um ``+warn``, ``+ban`` ou ``+kick``, a pessoa uparia uma Imagem/GIF, ou a Loritta indentificaria um link de alguma imagem que o Discord reconheça para ficar no Embed de Punição, assim podendo customizar as imagens que ficariam na punição sem ser a imagem que fica configurada pelo Administrador no Website da Loritta, __Caso a pessoa coloca-se uma Imagem/GIF inapropriada, baniria a pessoa de usar esse tipo de comando ou baniria de usar a Loritta__.

**Comment by MrPowerGamerBR** [comment]
Isto é algo que eu quis fazer antes para usarem no "motivo", caso uma imagem for colocada no motivo, ela usa na imagem da embed.
