### ISSUE TITLE
There is no file -fat.jar

### ISSUE THREAD

**Issue by mrranger** [LorittaBot/Loritta#2160]
Hello, I have a problem with the assembly that only loritta-parent-2020-SNAPSHOT is going to be assembled, but there is no file-fat.jar,

**Comment by xGabrielDEV** [comment]
You're trying to compile it or host it?

**Comment by xGabrielDEV** [comment]
If you want to host it, you'll need a file called "libs" with all dependencies, and get the fat jar here in releases tab or you can compile it using Gradle, ./gradlew build, and in the folder loritta-discord there will appear a new folder called build, then go to libs, there you'll find both versions, the fat one and the normal one.

**Comment by mrranger** [comment]
Thank you very much for the awesome bot, and for your work!

**Comment by MrPowerGamerBR** [comment]
Also, we do not give support selfhosted instances.

You can try to selfhost it (the readme explains everything) but any issue that you have we won't help.
