### ISSUE TITLE
Start message typo

### ISSUE THREAD

**Issue by arantesxyz** [LorittaBot/Loritta#2174]
https://github.com/LorittaBot/Loritta/blob/ba776384fa9e46c623e10af53e5e95dd200b4782/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/LorittaLauncher.kt#L50

It should be "I want to make **the** world a better place [...]"

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/pull/2175
