### ISSUE TITLE
Change the emoji of partner on +userinfo to the new badge

### ISSUE THREAD

**Issue by nestonfx** [LorittaBot/Loritta#2204]
Change the partner emoji on +userinfo to the new badge launched on the re-opening of Discord Partner Program.

**Comment by MrPowerGamerBR** [comment]
If anyone has the updated partner image in PNG format, I will fix it

**Comment by joaoesteves10** [comment]
https://cdn.discordapp.com/emojis/763378230387933204.png

**Comment by nneston** [comment]
owo very uwu

**Comment by MrPowerGamerBR** [comment]
Fixed
