### ISSUE TITLE
Run Repl.it

### ISSUE THREAD

**Issue by ghost** [LorittaBot/Loritta#2209]
```Run on Repl.it``` badge to the ```README``` This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about **Repl.it**

**Comment by MrPowerGamerBR** [comment]
I would need to check if repl.it is able to compile the project, kinda low priority since it is waaaay better to use IntelliJ IDEA to help the project.

**Comment by E-07** [comment]
it is true🙃

**Comment by SrGaabriel** [comment]
I think there's no need for this implementation, since repl.it probably doesn't support Gradle, so it'll be the same as coding on lower level text editors like VSCode.
