### ISSUE TITLE
Quote command

### ISSUE THREAD

**Issue by E-07** [LorittaBot/Loritta#2214]
![20201003_195335](https://user-images.githubusercontent.com/65204624/95003126-323b5980-05b2-11eb-9fd0-8de90ec89a35.jpg)
Comando não funciona no **DM**

**Comment by joaoesteves10** [comment]
Why would you want to quote a message in the DMs? You can't add Lori to a DM group chat, so you'd only be talking to yourself and quoting your own messages or lori's command responses

**Comment by joaoesteves10** [comment]
<:lori_thinking:741055999430885437>

**Comment by E-07** [comment]
Sla kk

**Comment by E-07** [comment]
Era pra pelo menos um "Esse comando não pode em dm" ou sla

**Comment by xGabrielDEV** [comment]
I think we should remove this command, since discord is planning to add a new reply type, and we already have the quoted one:
![image](https://user-images.githubusercontent.com/58668092/95451157-c5bbb400-093d-11eb-85cb-0f28c762d7d9.png)

**Comment by xGabrielDEV** [comment]
We should ask for @MrPowerGamerBR opinion about this.

**Comment by E-07** [comment]
Verdade ele ja não faz tanto sentindo assim.

**Comment by MrPowerGamerBR** [comment]
When inline replies are added I will remove the command
