### ISSUE TITLE
Duplicate Bug Hunter badge emoji on +userinfo if the user has the LVL2 badge with the Bug Hunter badge.

### ISSUE THREAD

**Issue by nestonfx** [LorittaBot/Loritta#2238]
bad bug

https://www.neston.fun/assets/Discord_VEMf4sztdz.png

**Comment by MrPowerGamerBR** [comment]
I need the one year bug hunter badge

**Comment by nestonfx** [comment]
https://cdn.discordapp.com/attachments/774064247311171605/775192261897617448/9552_BugHunterLvl2.png

there is owo

**Comment by MrPowerGamerBR** [comment]
Fixed
