### ISSUE TITLE
segurança da loritta

### ISSUE THREAD

**Issue by Jean-GM** [LorittaBot/Loritta#2241]
internamente a Loritta deveria ter algum tipo de criptografia isso impede que pessoas mas intencionadas acessem diretamente a Loritta e façam ações que ñ deveriam

**Comment by Jean-GM** [comment]
se tiver me avise

**Comment by MrPowerGamerBR** [comment]
Então dê um exemplo de algo que uma "pessoa má intencionada" possa fazer na Loritta.

**Comment by Jean-GM** [comment]
alterar as permissões de comandos como o +lorittaban alterar texto de comando para nsfw mas eu te intendo n tem muita coisa que o povo pode fazer em um bot to pensando em fechar esse issue

**Comment by SrGaabriel** [comment]
Na verdade é impossível de trocar as permissões dos comandos ou fazer alguma modificação no código-fonte da Loritta sem ter a aprovação do mantenedor do repositório, que no caso é o @MrPowerGamerBR.

**Comment by SrGaabriel** [comment]
@Jean-GM acredito que você pode fechar esse issue...

**Comment by Jean-GM** [comment]
valeu so estava preocupado com a segurança desse bot que eu gosto tanto

**Comment by MrPowerGamerBR** [comment]
@Jean-GM não tem jeito de alterarem o código do "+lorittaban" ou outros comandos assim sem que eu (ou outra pessoa que eu confio) aprove as mudanças antes.
