### ISSUE TITLE
LegacyBaseLocale to BaseLocale: loritta-discord vanilla commands

### ISSUE THREAD

**Issue by hechfx** [LorittaBot/Loritta#2245]
- [x] Administration
- [ ] Discord
   - [ ] [AvatarCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/AvatarCommand.kt)
   - [ ] [BotInfoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/BotInfoCommand.kt)
   - [ ] [ChannelInfoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ChannelInfoCommand.kt)
   - [ ] [EmojiCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/EmojiCommand.kt)
   - [ ] [InviteCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/InviteCommand.kt)
   - [ ] [InviteInfoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/InviteInfoCommand.kt)
   - [ ] [RemoveEmojiCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/RemoveEmojiCommand.kt)
   - [ ] [ServerInfoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ServerInfoCommand.kt)
- [ ] Economy
   - [ ] [LoraffleCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/LoraffleCommand.kt)
   - [ ] [PagarCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/PagarCommand.kt)
   - [ ] [SonhosCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/SonhosCommand.kt)
- [ ] Fun
   - [ ] [BemBoladaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/BemBoladaCommand.kt)
   - [ ] [CaraCoroaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/CaraCoroaCommand.kt)
   - [ ] [CongaParrotCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/CongaParrotCommand.kt)
   - [ ] [FaustaoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/FaustaoCommand.kt)
   - [ ] [GameJoltCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/GameJoltCommand.kt)
   - [ ] [PedraPapelTesouraCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/PedraPapelTesouraCommand.kt)
   - [ ] [QualidadeCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/QualidadeCommand.kt)
   - [ ] [TioDoPaveCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/TioDoPaveCommand.kt)
   - [ ] [TwitchCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/TwitchCommand.kt)
   - [ ] [VaporQualidadeCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/VaporQualidadeCommand.kt)
   - [ ] [VaporondaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/VaporondaCommand.kt)
   - [ ] [VemDeZapCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/VemDeZapCommand.kt)
- [ ] Images
   - [ ] [AmigosCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/AmigosCommand.kt)
   - [ ] [AmizadeCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/AmizadeCommand.kt)
   - [ ] [CepoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/CepoCommand.kt)
   - [ ] [ContentAwareScaleCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/ContentAwareScaleCommand.kt)
   - [ ] [DemonCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/DemonCommand.kt)
   - [ ] [DeusCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/DeusCommand.kt)
   - [ ] [DiscordiaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/DiscordiaCommand.kt)
   - [ ] [GangueCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/GangueCommand.kt)
   - [ ] [GumballCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/GumballCommand.kt)
   - [ ] [InverterCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/InverterCommand.kt)
   - [ ] [KnuxThrowCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/KnuwThrowCommand.kt)
   - [ ] [LaranjoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/LaranjoCommand.kt)
   - [ ] [LavaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/LavaCommand.kt)
   - [ ] [LavaReversoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/LavaReversoCommand.kt)
   - [ ] [PerdaoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/PerdaoCommand.kt)
   - [ ] [PerfeitoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/PerfeitoCommand.kt)
   - [ ] [PrimeirasPalavrasCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/PrimeiraPalavrasCommand.kt)
   - [ ] [RazoesCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/RazoesCommand.kt)
   - [ ] [RipVidaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/RipVidaCommand.kt)
   - [ ] [SwingCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/SwingCommand.kt)
   - [ ] [TextCraftCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TextCraftCommand.kt)
   - [ ] [TodoGrupoTemCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TodoGrupoTemCommand.kt)
   - [ ] [TretaNewsCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TretaNewsCommand.kt)
   - [ ] [TriggeredCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TriggeredCommand.kt)
   - [ ] [TrumpCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TrumpCommand.kt)
- [ ] Minecraft
   - [ ] [McAvatarCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McAvatarCommand.kt)
   - [ ] [McBodyCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McBodyCommand.kt)
   - [ ] [McConquistaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McConquistaCommand.kt)
   - [ ] [McHeadCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McHeadCommand.kt)
   - [ ] [McMoletomCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McMoletomCommand.kt)
   - [ ] [McSkinCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McSkinCommand.kt)
   - [ ] [McStatusCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McStatusCommand.kt)
   - [ ] [McUUIDCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McUUIDCommand.kt)
   - [ ] [OfflineUUIDCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/OfflineUUIDCommand.kt)
   - [ ] [SpigotMcCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/SpigotMcCommand.kt)
- [ ] Misc
   - [ ] [AjudaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/AjudaCommand.kt)
   - [ ] [EscolherCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/EscolherCommand.kt)
   - [ ] [PatreonCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/PatreonCommand.kt)
   - [ ] [PingCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/PingCommand.kt)
   - [ ] [QuoteCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/QuoteCommand.kt)
- [ ] Music
   - [ ] [LyricsCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/music/LyricsCommand.kt)
- [ ] Pokemon
   - [ ] [PokedexCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/pokemon/PokedexCommand.kt)
- [ ] Roblox
   - [ ] [RbGameCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/roblox/RbGameCommand.kt)
- [ ] Social
   - [ ] [AfkCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/AfkCommand.kt)
   - [ ] [BackgroundCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/BackgroundCommand.kt)
   - [ ] [DivorceCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt)
   - [ ] [EditarXPCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/EditarXPCommand.kt)
   - [ ] [GenderCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/GenderCommand.kt)
   - [ ] [MarryCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/MarryCommand.kt)
   - [ ] [PerfilCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/PerfilCommand.kt)
   - [ ] [RankCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/RankCommand.kt)
   - [ ] [RepCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/RepCommand.kt)
   - [ ] [SobreMimCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/SobreMimCommand.kt)
- [ ] Utils
   - [ ] [DicioCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/DicioCommand.kt)
   - [ ] [EncodeCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/EncodeCommand.kt)
   - [ ] [KnowYourMeme](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/KnowYourMemeCommand.kt)
   - [ ] [MoneyCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/MoneyCommand.kt)
   - [ ] [OCRCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/OCRCommand.kt)
   - [ ] [PackageInfoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/PackageInfoCommand.kt)
   - [ ] [TempoCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/TempoCommand.kt)
   - [ ] [TranslateCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/TrranslateCommand.kt)
   - [ ] [WikipediaCommand](https://github.com/LorittaBot/Loritta/blob/development/loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/WikipediaCommand.kt)

- There are all commands from `loritta/commands/vanilla`

![image](https://cdn.discordapp.com/emojis/706263175892566097.gif)

**Comment by MrPowerGamerBR** [comment]
Superseded by https://github.com/LorittaBot/Loritta/issues/2262
