### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by Jean-GM** [LorittaBot/Loritta#2251]
eae power a loritta tem um problema de quando ela fala quanto falta pra atingir a meta de doaçãoe se passa o valor de doações ela  fala: faltam -x para atingir a meta de doações

**Comment by Jean-GM** [comment]
exemplo se ela teve 6087 doações e a meta e 6000 ela falaria: faltam -87 doações pra atingir a meta desse mês

**Comment by MrPowerGamerBR** [comment]
Isso não tem nada a ver com a Loritta (o bot)
