### ISSUE TITLE
Transaction reason "profile layout" is missing [5 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2253]
Currently it shows up as "background" instead of "profile layout" in the `+transaction`

**Comment by barddoo** [comment]
Could you give more details?

**Comment by MrPowerGamerBR** [comment]
1. Buy a profile layout in Loritta's website
2. Check your `+transaction`
3. Loritta will say that you bought a background instead of a profile layout

To fix this: A new entry in the `SonhosPaymentReason` must be added (`PROFILE_LAYOUT`), add the string to the locales and then change Loritta to use the new SonhosPaymentReason type instead of using `BACKGROUND`

**Comment by Aleixopi15** [comment]
Interesting that but I'm learning JDA, Kotlin now, but one day I hope to help
