### ISSUE TITLE
Remove old command framework API [24 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2255]
Currently there is three APIs:

1. The very old one, `AbstractCommand` API `com.mrpowergamerbr.loritta.commands`
2. The old one that uses the `command-framework` lib
3. The new one that uses Kotlin DSL

Maintaining all of those three APIs is a pain, so it would be nice to remove the `2` API because:
* Uses a LOT of Reflection
* There is not a lot of commands that still rely on that API

**Commands that needs to be migrated:**
* [x] `ChannelInfoCommand` (requires channel parsing)
* [x] `PluginsCommand`
* [x] `DashboardCommand`
* [x] `GuildBannerCommand`
* [x] `RoleInfoCommand`
* [x] `ScratchCardCommand`
* [x] `ScratchCardTopCommand`
* [x] `AsciiCommand`
* [x] `AtendenteCommand`
* [x] `DrawnWordCommand`
* [x] `EmojiMashupCommand`
* [x] `TristeRealidadeCommand`
* [x] `FanArtsCommand`
* [x] `GiveawayCommand`
* [x] `GiveawaySetupCommand`
* [x] `GiveawayRerollCommand`
* [x] `GiveawayEndCommand`
* [x] `RenameChannelCommand`
* [x] `RenameEmojiCommand`
* [x] `DocesCommand` (can be removed)
* [x] `LoriToolsQuirkyStuffCommand` (can be removed)
* [x] `SouTopDoadorCommand` (can be removed because nobody uses this)

(Each fixed command = +1,5 BRL in the bounty)

**Comment by SrGaabriel** [comment]
Currently working on this.

**Comment by SrGaabriel** [comment]
Since @hechfx was already working on this issue, I will try to fix another ones.
