### ISSUE TITLE
Fix "+clear" message not showing up [5 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2271]
When using "+clear", the "Chat cleared sucessfully" doesn't show up because Loritta tries to reply to a deleted message.

Instead of using `context.reply(...)`, we need to use `context.message.channel.sendMessage(*message here*)`, to avoid the reply made by the `context.reply` code.

**Comment by SrGaabriel** [comment]
Working on this.
