### ISSUE TITLE
Send a DM when a divorce happens [10 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2289]
If `user1` divorces with the `+divorce` command, a DM should be sent to `user2` saying "user1 divorced you!"

Because there is a lot of people that complain "my marriage disappeared fix your bot" when in reality the other user divorced.

**Comment by iiAmFilippi** [comment]
Working on this

**Comment by LeonidioJose** [comment]
Ok !
