### ISSUE TITLE
Show who the user won/lost against in coin flip bet in the "+transaction" [10 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2293]
The information is already being saved in the database on the sonhos transaction log. Check how the `SonhosPaymentReason.PAYMENT` was implemented and do the same thing for the `SonhosPaymentReason.COIN_FLIP_BET`

Just keep the same format as the `PAYMENT` (user + discriminator + id).

The locales will need to be updated for this

**Comment by SrGaabriel** [comment]
I will try to do this one.

**Comment by MrPowerGamerBR** [comment]
Already implemented
