### ISSUE TITLE
Improvements to the "+transaction" command [40 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2294]
This *will* have a bounty later, but for now this is just ideas for how it can be improved.

**Stuff that I want to be added:**
* A way to do user filtering, allowing you to see payments from user X to user Y
* A way to see payments for a specific reason, example: Checking only coin flip bets
* Add pagination (up to 100 pages, see ranking command)

However I'm not sure how that can be implemented in the command itself in a way that would be nice.

**Comment by hechfx** [comment]
I have some ideas to do this:

- See your transactions with filter. (ex: `+transactions only:coinflipbet`)

- See other users' transactions with filter. (ex: `+transactions <@123170274651668480> only:coinflipbet`)

- See pages of your transactions with filter. (ex: `+transactions only:coinflipbet 3`)

- See pages of other users' transactions with filter. (ex: `+transactions<@!123170274651668480> only:coinflipbet 3`)

- See pages of your transactions to other users with filter. (ex: `+transactions to:123170274651668480 only:coinflipbet 3`)

- See pages of other users' transactions to other users with filter. (ex: `+transactions <@!123170274651668480> to:236167700777271297 only:coinflipbet 3`)
