### ISSUE TITLE
Force both users accept the "+coinflip bet" [40 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2303]
**Original Suggestion:** https://canary.discord.com/channels/297732013006389252/359139508681310212/787725990838665216

Make "+coinflip bet" work like how the "+pay" works: Both users need to approve the bet before it can happen.

This is also nice because users can "cancel" the bet if they want to, killing two birds with one stone.

**Comment by jaxxibae** [comment]
> This is also nice because users can "cancel" the bet if they want to, killing two birds with one stone.

Nice trocadilho, will consider doing this
