### ISSUE TITLE
Locale issue when selling stocks

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2317]
![image](https://user-images.githubusercontent.com/9496359/102925667-97487200-4472-11eb-8f3d-8863ffe4b206.png)

**Comment by iiAmFilippi** [comment]
Could you describe the problem more? I could not understand.

**Comment by MrPowerGamerBR** [comment]
@iiAmFilippi "Sempre fique de olho no `+broker portifolio` para saber se vale a pena vender", currently it is showing the loss.

This is probably an issue in the locales, where instead of `{3}` (I guess, not really sure) it is `{2}` or something like that.

**Comment by MrPowerGamerBR** [comment]
Fixed by @iiAmFilippi
