### ISSUE TITLE
Add "sell all" for the "+broker sell" command [20 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2319]
`+broker sell OIBR3 all` would sell all of your stocks for OIBR3

**Comment by ArthurProgrammer** [comment]
I will try to do this one

**Comment by ArthurProgrammer** [comment]
@hechfx will do this

**Comment by hechfx** [comment]
Done

**Comment by MrPowerGamerBR** [comment]
Done https://github.com/LorittaBot/Loritta/commit/c4e836cf8679722aea683d0063bae18b6ba8aa49
