### ISSUE TITLE
Block mentioning everyone in reputation command.

### ISSUE THREAD

**Issue by princessmortix** [LorittaBot/Loritta#2323]
If you use +rep @everyone the bot will return a error message **mentioning everyone**, allowing users to spam ping in servers. Image showing the bug below ↓

![Screenshot_20201227-020230](https://user-images.githubusercontent.com/47502554/103171097-25807780-4828-11eb-9b18-80e13e1f3620.png)

(Thanks to Vic for providing the image.)

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/commit/a25ce06f023317c08ae31f7f1a2732a619ff6022
