### ISSUE TITLE
Increase giveaway user limits

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2326]
20 is kinda low, but calculations needs to be made to know how much it can fit in a message

**Comment by FilipoDEV** [comment]
There is no way to know exactly how many mentions fit in the message because the ids vary in size later on possibly Discord will increase the size of the ids. Not to mention the newer user ids that make the calculation even more unbalanced.

**Comment by FilipoDEV** [comment]
But well, I did the calculations and my result was: 48 winners.
I considered the size of the largest number of characters that can exist in a user's id today and the size of characters that can exist in the title of an embed which is 256 characters.

**Comment by MrPowerGamerBR** [comment]
Implemented in https://github.com/LorittaBot/Loritta/commit/4df044b221a4e1250f4bc80c5265ae34c21bd76a
