### ISSUE TITLE
Add pagination to "+transactions" [20 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2328]
From https://github.com/LorittaBot/Loritta/issues/2294

(@hechfx already made this)

**Comment by hechfx** [comment]
![779845380736679956](https://user-images.githubusercontent.com/60321993/103323059-e452b800-4a1f-11eb-8f8c-86e98976fc10.gif)

**Comment by MrPowerGamerBR** [comment]
Implemented in https://github.com/LorittaBot/Loritta/issues/2294
