### ISSUE TITLE
Move everything from "com.mrpowergamerbr.loritta" to "net.perfectdreams.loritta" [40 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2330]
There is no point in keeping two different packages.

The issue is that it is not possible to just use IntelliJ IDEA's "Refactor" to change the package, because there are files with the same name in the two packages.

**Comment by nekkan** [comment]
.

**Comment by MrPowerGamerBR** [comment]
I think this is not necessary anymore, currently having both packages creates a nice split between "old code that needs to be rewritten" and "new code which is still kinda old"
