### ISSUE TITLE
Add coinflip bet users to the "+transactions" command [20 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2331]
Just like how `+pay` shows who paid and received the sonhos, it would be cool if `+coinflip bet` also was shown in the `+transactions` command.

The information is already being stored, the only thing that is needed to be done is:
1. Copy the code that handles the `+pay` in the `+transactions` and adjust it for the `+coinflip bet`
2. Update the locales

**Comment by FilipoDEV** [comment]
I will try to do this one

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/commit/9b97b4d8f582bfa45131adf5e9cd891cd965413a
