### ISSUE TITLE
Change +ship embed color dynamically [20 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2345]
The embed color should change dynamically depending on how much % you have in the ship, example:

If the ship is 100%, it should show the current color
If the ship is 0%, it should show black
Then just interpolate the values between 0% and 100% (shouldn't be that hard, maybe just multiply the rgb values!)

**Comment by Lucasmellof** [comment]
Working on this.

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/pull/2357
