### ISSUE TITLE
Use correct gender pronouns when a user wins the bd&c [20 BRL]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#2348]
![image](https://user-images.githubusercontent.com/9496359/104675943-386ac700-56c5-11eb-8291-b4d2edc9bfb4.png)

https://cdn.discordapp.com/attachments/359139508681310212/798331781581504512/unknown.png

**Comment by hechfx** [comment]
i'll do

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/pull/2352
