### ISSUE TITLE
cocielochaves

### ISSUE THREAD

**Issue by VinicmTV** [LorittaBot/Loritta#2401]
The command is not responding. Loritta is returning a 0-byte file

**Comment by MrPowerGamerBR** [comment]
Fixed

**Comment by VinicmTV** [comment]
I went to test here. And it's still returning the 0-byte file

**Comment by MrPowerGamerBR** [comment]
Now it should work, the container disk was full so it was causing issues, and looks like it was still causing issues after I tried cleaning it up.
