### ISSUE TITLE
Facilitar likes

### ISSUE THREAD

**Issue by BernardoPC-Dev** [LorittaBot/Loritta#2405]
Eu acho horrivel q a pessoa tem que ir no github pra dar like, poderia ser pelo discord msm, like na msg do github bot

**Comment by MrPowerGamerBR** [comment]
Não, eu não vou fazer dois lugares diferentes para votarem em algo, especialmente como o GitHub permite VER QUAIS SÃO AS SUGESTÕES MAIS VOTADAS.

E aliás, este repositório não é para ficar dando sugestões bobas, existe o DreamLand (que é o REPOSITÓRIO QUE VOCÊ ESTÁ RECLAMANDO) para isso.
