### ISSUE TITLE
Comando +hora

### ISSUE THREAD

**Issue by BernardoPC-Dev** [LorittaBot/Loritta#2414]
Podia ter um comando tipo, +hora <país/utc> e mostra, ou o utc e a hora desse pais, ou os paises que usam esse utc

**Comment by MrPowerGamerBR** [comment]
Quantas vezes eu tenho que dizer para você que **sugestões devem ser enviadas no repositório de sugestões**? Já que é a segunda vez e a próxima você será banido.

https://github.com/LorittaBot/DreamLand/issues

E ainda, sugestão duplicada: https://github.com/LorittaBot/Loritta/issues/2299
