### ISSUE TITLE
Sistema de Rank

### ISSUE THREAD

**Issue by Azrael3301** [LorittaBot/Loritta#2415]
É possível retirar Ou adicionar uma certa quantidade de pontos ( XP ) a um usuário?
Exemplo: +unrank -5000 XP {user}
+addrank 1000 xp {user} 

No meu servidor a grande maioria usa mais o sistema de call e call não dá XP, então queria uma forma de adicionar XP ( mesmo que seja uma quantidade limitada ) para esses Usuários.

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/DreamLand

E o servidor de suporte não é aqui.
