### ISSUE TITLE
Problema no +traduzir

### ISSUE THREAD

**Issue by SOekd** [LorittaBot/Loritta#2418]
É possível mandar convites de outros servidores usando o comando +traduzir (mesmo com o bloqueador de convites ativado).

https://prnt.sc/12z879y

**Comment by MrPowerGamerBR** [comment]
Isso só acontece se o servidor não utiliza o sistema de bloqueador de convites da Loritta, já que se usa, a Loritta verifica se a mensagem tem um invite antes de executá-lo.

**Comment by SOekd** [comment]
Ao que parece, quando ativa a mensagem de aviso ele bloqueia corretamente, mas quando tira a mensagem da para burlar.

https://www.youtube.com/watch?v=xFF1ZSHC_AE
