### ISSUE TITLE
Números em morse estão errados

### ISSUE THREAD

**Issue by brnd-21** [LorittaBot/Loritta#2431]
Quando a loritta vai codificar números para o morse e vice-versa, ela utiliza de caracteres errados para os pontos

O resultado disso leva a um erro se tentarmos decodificar isso usando outra ferramenta.

Ex: +morse abc 123, leva ao resultado ( .- -... -.-. / ·---- ··--- ···-- ), ao invés de ( .- -... -.-. / .---- ..--- ...-- )

Chequei em vários lugares, e representam em morse tanto com o ···-- quanto com ...--
Mas há essa inconsistência nos números da loritta, poderiam padronizar igual os outros caracteres?

![image](https://user-images.githubusercontent.com/56841881/120076382-9946da80-c07b-11eb-87bb-f43dce7e25ae.png)

**Comment by MrPowerGamerBR** [comment]
Bugs devem ser reportados primeiramente no repositório DreamLand, e não no repositório da Loritta: https://github.com/LorittaBot/DreamLand

**Comment by MrPowerGamerBR** [comment]
Corrigido em https://github.com/LorittaBot/Loritta/commit/ac571fcb0fa10b6aec3f82cc7a0b29f0904a2046
