### ISSUE TITLE
Reputação

### ISSUE THREAD

**Issue by valerian1237** [LorittaBot/Loritta#2440]
Não sei se tem como mas se não tiver poderia dar para remover reputação de alguém, exemplo alguém que já não foi uma boa pessoa

**Comment by PeterStark000** [comment]
Este repositório não é um lugar ideal para fazer sugestões, se você quer sugerir alguma funcionalidade nova ou comando novo para a Loritta sugira no https://github.com/LorittaBot/DreamLand
