### ISSUE TITLE
Maybe Change the Repo General Language to English

### ISSUE THREAD

**Issue by moelrobi** [LorittaBot/Loritta#251]
Hello dear Loritta team,

since i am a open source developer i like the idea of publishing code to the public. However now since Loritta is a wide spread Discord Bot i also would like to contribute to the Repo, but just cant since i dont understand a word in the README or most of the Issues here on the Repo.

If there would be no problem i think there would be a lot more users if the Repo general Language would be English. :thinking:

**Comment by MrPowerGamerBR** [comment]
I will translate the readme soon
