### ISSUE TITLE
• Adicionar regra de Spoilers

### ISSUE THREAD

**Issue by zYuri23** [LorittaBot/Loritta#254]
Adicionar uma regra de Spoilers ao servidor de suporte. Ninguém é obrigado a aguentar spoilers desnecessários, principalmente de pessoas que sabem que o membro se incomoda com o Spoiler e ainda posta ele

**Comment by MrGaabriel** [comment]
Se encaixa na regra de irritar ou provocar outros usuários. Não é necessário adicionar outra regra só para isso.

**Comment by Luk3HD** [comment]
antes tinha nas regras isso, mas em forma de comentário...
