### ISSUE TITLE
Alguns emojis da loritta não aparecem mais!

### ISSUE THREAD

**Issue by sebastianjnuwu** [LorittaBot/Loritta#2567]
Como visto logo abaixo alguns dos emojis da lorita não estão aparecendo nas mensagens dela ;-;
![](https://media.discordapp.net/attachments/982952386001776673/983374678653550632/Screenshot_20220606-111829.jpg)

**Comment by MrPowerGamerBR** [comment]
Você não deu permissão de usar emojis externos no cargo de `@everyone`
