### ISSUE TITLE
Bug command "/text lowercase"

### ISSUE THREAD

**Issue by Coork** [LorittaBot/Loritta#2576]
O comando "lowercase" apresenta um bug que permite a inserção de links. Exemplo:
`/text lowercase text:https://discord.gg/loritta`

Mesmo comportamento para os comandos "uppercase" e "clap".

**Comment by MrPowerGamerBR** [comment]
Fixed in b31239a49fb1ac88fb73d94cab0cc0b4d63bbe7c
