### ISSUE TITLE
Stuck in another language

### ISSUE THREAD

**Issue by AToska21** [LorittaBot/Loritta#2586]
Hi! I'm self hosting the cinnamon branch of Loritta but whenever I use the bot it seems to be in another language. I didn't file a /language command and no option in the .conf file. What do I do to switch Loritta to English (for my whole server)?

**Comment by MrPowerGamerBR** [comment]
Currently the only way to change the language is by self-hosting the Legacy instance and using `+language`

**Comment by AToska21** [comment]
> Currently the only way to change the language is by self-hosting the Legacy instance and using `+language`

so i tried that and got this:
Caused by: org.postgresql.util.PSQLException: ERROR: relation "reminders" does not exist
