### ISSUE TITLE
Bypass anti-invite with anagram command

### ISSUE THREAD

**Issue by coork** [LorittaBot/Loritta#2599]
Guild invite filter not working with some slash commands.

![image](https://user-images.githubusercontent.com/106634045/188961997-5bde53c9-a258-461b-8e28-1fb82af93e15.png)

**Comment by coork** [comment]
b31239a está funcionando?

**Comment by coork** [comment]
![image](https://user-images.githubusercontent.com/106634045/188974644-d3afc711-360f-4fbc-be01-d8508aa18185.png)

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/commit/8d3bdedce8a289c5bbbc90160865781dadee7703, but I think the clean up system can still be improved further
