### ISSUE TITLE
Adicionar Giveaways/Sorteios

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#26]
Adicionar um sistema de giveaways, customizável pela a pessoa que executou o comando.

## Como irá funcionar?
Ao digitar `+giveaway`, a Loritta irá fazer algumas perguntas sobre o giveaway, como...
1. Qual será o nome do giveaway?
2. Qual será a descrição do giveaway?
3. Qual canal irá acontecer o giveaway?
4. O giveaway irá durar até quando?
5. Quantos usuários irão vencer o giveaway?
6. Qual emoji será usado nas reações do giveaway

Após acabar o giveaway, a Loritta irá anunciar quem ganhou o sorteio

**Comment by Pedro12315** [comment]
O comando giveway não está pegando

**Comment by MrPowerGamerBR** [comment]
@Pedro12315 eu acabei de usar e está funcionando corretamente
