### ISSUE TITLE
Texto de timeout incorreto

### ISSUE THREAD

**Issue by TheMhv** [LorittaBot/Loritta#2650]
O texto de timeout no comando `+bal` está incorreto, o contador adiciona o invés de subtrair

![image](https://github.com/LorittaBot/Loritta/assets/25031483/020e5de0-df69-4df6-9d19-855d4e473b9e)
![image](https://github.com/LorittaBot/Loritta/assets/25031483/e0567e32-daaf-4514-826f-45b9a1ad4841)

**Comment by MrPowerGamerBR** [comment]
O relógio do seu computador está errado, ou você está vendo uma mensagem de cooldown que ela enviou no passado, já que o Discord automaticamente atualiza o texto do tempo automaticamente.
