### ISSUE TITLE
Update selfhosting.md please i want to selfhost loritta

### ISSUE THREAD

**Issue by bloodieee** [LorittaBot/Loritta#2655]

**Comment by hechfx** [comment]
Okay, so here's a little ✨ tutorial ✨ for you.

## Selfhost while coding:
- Clone the repository;
- Open the project with [IntelliJ IDEA](https://www.jetbrains.com/idea/);
- Let it build (If you don't have a good PC, this step will be slower);
- Navigate to `LorittaLauncher.kt`, then you need to start the main method;
- The first start will generate a configuration file that you need to fill it up and restart the main method to get your selfhost running;
- Voilà, your selfhost is running.

## Selfhost with Docker
- You will need to learn how to use Docker and I will not teach you, search up on the internet.

**Comment by hechfx** [comment]
https://github.com/LorittaBot/Loritta/blob/main/docs/SELF-HOSTING.md

**Comment by bloodieee** [comment]
> https://github.com/LorittaBot/Loritta/blob/main/docs/SELF-HOSTING.md

damn thanks, i didn't know they added it back
thank you for your time
