### ISSUE TITLE
Adicionar "+punishmentlist"

### ISSUE THREAD

**Issue by MrGaabriel** [LorittaBot/Loritta#27]
Adicionar um comando semelhante ao "+warnlist"

## Como irá funcionar?
Funcionará exatamente como o "+warnlist", só que desta vez guardando as punições como mute, kick, softban, etc

**Comment by OswaldoDayJr** [comment]
Dica para adaptação pro português: +listadepunicao

**Comment by MrGaabriel** [comment]
Que tal +punições?
