### ISSUE TITLE
Permitir escolher o que acontece quando um streamer troca de jogo

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#270]
Atualmente a Lori apenas está ignorando trocas de jogo, seria legal escolher o que acontece ao trocar!

**Comment by Ari12332178** [comment]
CRIA ISSO AGR PORRA ;) VLW

**Comment by Ari12332178** [comment]
Salve galera do AP da Loritta sou o AriG4M3R <@541853913813352491> (eh eu tentei me citar)

**Comment by Ari12332178** [comment]
Desculpa quem acreditou em mim... MENTIRA AAA EU CONSIGO SIM PORRA

<@186799338767384576> LINDO FALEI

**Comment by MrGaabriel** [comment]
Não use a seção de comentários para escrever coisas non-sense
