### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#29]
Adicionar sistema de timers.

## Como irá funcionar?
Será possível configurar mensagens automáticas no painel da Loritta, sendo possível configurar...
1. Quais mensagens serão enviadas no timer
* Deverá ser possível configurar se serão enviadas em ordem aleatória ou sequêncial, caso tenha mais de uma mensagem configurada
2. Em qual canal será enviado a mensagem automática
3. A cada quanto tempo a mensagem será enviada?
* Será permitido configurar se a mensagem só será enviada em um dia específico, ou até dias da semana específicos.

**Comment by OswaldoDayJr** [comment]
Top!
