### ISSUE TITLE
Acho que a loritta devia ter um sistema de level tipo mee6 ai sim seria mu...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#292]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/515307513722175498/b231f410098bc046d32f70e466c1e530.png">

**Sugestão de `Asriel Dreemurr#8397` (`515307513722175498`)**
**ID da Mensagem: `359139508681310212-541045395179175957`**

<hr>

Acho que a loritta devia ter um sistema de level tipo mee6 ai sim seria muito bom <img src="https://cdn.discordapp.com/emojis/378551064313724928.png" width="16">

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
