### ISSUE TITLE
Adicionar sistema de locale do usuário

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#30]
Atualmente a Loritta apenas suporta que servidores definem qual é a linguagem que eles usam, mas também seria interessante que usuários pudessem colocar a "linguagem de preferência" deles, caso eles coloquem uma linguagem, a Loritta irá responder na linguagem de preferência que eles colocaram, em vez de usar a linguagem padrão do servidor.

**Comment by OswaldoDayJr** [comment]
Esse ae é perfeito!!!
