### ISSUE TITLE
Consertar esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#302]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/318067976689680384/71f58c74a501b082b3237e49e75a5fb4.png">

**Sugestão de `Mariazinha#0963` (`318067976689680384`)**
**ID da Mensagem: `359139508681310212-540700458914807809`**

<hr>

Consertar esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/540700444855500810/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/540700444855500810/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido quando o sistema de ações foi refeito. (Relacionado ao bug no JDA de 0 bytes)
