### ISSUE TITLE
Recompensas & Level

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#303]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/364272709317951488/b5fafdb79b45bbd8d2efd98b28bf12ab.png">

**Sugestão de `Syros#1974` (`364272709317951488`)**
**ID da Mensagem: `359139508681310212-540695005765828619`**

<hr>

***Recompensas & Level***

```diff
Já que o Mee6 ficou premium na parte de recompensas, até que seria útil por nos levels da Loritta..```

***Explicando melhor:***
```Diff
MEE6 Ficou Pago em algumas funções e como isso aconteceu a Loritta vai ser bem útil no momento, devia ter como botar recompensas de level em seu servidor, ou configurar a quantia de XP a cada mensagem.. Assim então ter como configurar boa parte dos level da loritta.```

***É isso ,-,***

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
