### ISSUE TITLE
Ter uma função de nível que nem o mee6 para dar cargos etc...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#313]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/514868327525646346/650d07190a9d6db4d53f08bfcb8aed22.png">

**Sugestão de `purple guy#3837` (`514868327525646346`)**
**ID da Mensagem: `359139508681310212-540435374799847455`**

<hr>

Ter uma função de nível que nem o mee6 para dar cargos etc...

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
