### ISSUE TITLE
Sistema de cargos temporários

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#32]
Cargos temporários já existem no comando de `+mute`, mas seria melhor fazer algo mais "genérico" para que outros módulos e comandos possam criar e gerenciar cargos temporários.

### Adicionar Cargos
`+cargotemp add @nomedocargo <@172782058396057602> <@!123170274651668480> `

Vai adicionar 1 usuário ou mais no cargo e depois do tempo definido irá remover automaticamente o usuário do cargo, semelhante ao comando do mute, mas este você vai definir qual cargo.

### Retirar Cargos
`+cargotemp remover @nomedocargo <@172782058396057602> <@!123170274651668480>`
Vai remover  1 usuário ou mais do cargo e depois do tempo definido vai adiciona-lós no cargo automaticamente

### Formato de Cargos
**@nome do cargo:** O mais "user friendly", mas a maioria dos cargos não possuem as notificações de cargos ativas.
**nome do cargo:** O problema vai ser os espaços, já que é possível adicionar múltiplos cargos no mesmo comando.
**ID do cargo:** O jeito mais simples, mas o menos prático para usuários, é possível pegar o ID de um cargo utilizando `+roleid`

Exemplo de verificação de vários cargos de diferente tipos...
```kotlin
// Cargos deverão ser processados dependendo se o cara marcou o cargo ou só colocou parte do nome
val roles = mutableListOf<Role>()

run {
	val rolesSplit = rolesStr.split(", ")
	val names = mutableListOf<String>()

	for (part in rolesSplit) {
		if (part.startsWith("<@&") && part.endsWith(">")) {
			roles.add(context.guild.getRoleById(part.substring(3, part.length - 1)))
			continue
		}
		if (part.isValidSnowflake()) {
			roles.add(context.guild.getRoleById(part))
			continue
		}
		names += part
	}

	for (name in names) {
		if (name.isNotEmpty())
			roles.addAll(context.guild.getRolesByName(name, true))
	}
}
```

**Comment by gabrielpjrt** [comment]
Pode adicionar +1 cargo separando com " | "
