### ISSUE TITLE
Concertar esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#320]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/a2a59b93710a87856c99fdad91a54407.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-540261265352818699`**

<hr>

Concertar esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/540261260214796370/Screenshot_2019-01-30-18-04-56.png](https://cdn.discordapp.com/attachments/359139508681310212/540261260214796370/Screenshot_2019-01-30-18-04-56.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido.
