### ISSUE TITLE
poderia ter um esquema de levels pra nao precisar usar outros bots

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#333]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/396320290088419328/c3f294b4d72d68027ee563cc9f5451e7.png">

**Sugestão de `KAUE#3557` (`396320290088419328`)**
**ID da Mensagem: `359139508681310212-538410639106768906`**

<hr>

poderia ter um esquema de levels pra nao precisar usar outros bots

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
