### ISSUE TITLE
Refazer o sistema de verificação de RSS Feeds

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#34]
O sistema atual é mal feito comparado com a verificação de posts do Amino, sem contar que tem um delay colossal para verificar cada feed.

Seria melhor retirar o jsoup para verificações de RSS Feed e substituir por uma library feita para parsear RSS feeds.

**Comment by MrGaabriel** [comment]
https://github.com/rometools/rome
