### ISSUE TITLE
Já que o @? deletou

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#348]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/123170274651668480/a_e02347a3c2ebc1830ae47e836556d6ca.gif">

**Sugestão de `MrPowerGamerBR#4185` (`123170274651668480`)**
**ID da Mensagem: `359139508681310212-542701146662371329`**

<hr>

Já que o <@347064573318135811> deletou:

Quando alguém errar um comando da Lori (por exemplo: `+dailie` em vez de `+daily`), ela poderia verificar os comandos mais "parecidos" com o que o usuário escreveu e falar "Hey, talvez você quis dizer `+daily`!)

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/pull/365
