### ISSUE TITLE
Acho que podia tirar o Re Captcha do +daily porque pra entrar na conta já ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#358]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/376856858025263105/374af47f1686a2b5092973175c8fc909.png">

**Sugestão de `๖ۣۜNew™#8618` (`376856858025263105`)**
**ID da Mensagem: `359139508681310212-542777109135884299`**

<hr>

Acho que podia tirar o Re Captcha do ``+daily`` porque pra entrar na conta já pede o Re Captcha então não tem muita necessidade. _Também pra deixar mais rápido o processo_

**Comment by MrPowerGamerBR** [comment]
A Lori pede reCAPTCHA ao pegar o daily para evitar automatização de daily.

(E também para verificar se o usuário não está usando VPNs/proxies/etc)
