### ISSUE TITLE
Sistema de economia como funcionar! (Sugestão)

### ISSUE THREAD

**Issue by OswaldoDayJr** [LorittaBot/Loritta#36]
**Sugestão:**

No sistema de economia que já há uma página feita na [Loritta canary](canary.loritta.website) ter opção ao criar um item na logia dar roles pode ser permanente ou temporário (Dica incluir opções de tempo tanto personalizado[Escrevendo "10 minutos"] ou tempos em um rótulo[Opções em um caixinha com tipo "1 Dia, 5 Dias, 1 Mês"] isso se os tempos longos forem possível na Loritta)

**Comment by MrPowerGamerBR** [comment]
Em espera até a #32 ser implementada.
