### ISSUE TITLE
Permissão para usar comandos

### ISSUE THREAD

**Issue by slaick** [LorittaBot/Loritta#37]
As vezes é interessante que somente membros específicos utilizem certos comandos, seria interessante na configuração dela pudéssemos dizer quais cargos poderiam ou não utilizar tais comandos.

**Comment by OswaldoDayJr** [comment]
Aprovo!

**Comment by slaick** [comment]
Saquei! Realmente, meus conhecimentos de programação são insuficientes para dar qualquer opinião sobre, kkkkk

**Comment by paulocrash** [comment]
Aprovo, acredito que seria melhor se toda a configuração fosse feita no painel dela, exemplo.

http://prntscr.com/lmylya

Como pode ver tenho todos os comandos ativo, seria perfeito se só certos cargos poderem usar tal comando.

`!faustao` - Somente cargos DONOS;
`!bolsonaro` - Somente cargos ADMIN para cima;

Ai no caso configura na própria aba de Comandos, seleciona os comandos e qual cargo vai ter acesso ao comando.
