### ISSUE TITLE
{Sugestão} Criação de salas privadas automáticas.

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#371]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/343452315535147009/76d58fa65dec51f10fbf6f4775860165.png">

**Sugestão de `Oswaldo#8984` (`343452315535147009`)**
**ID da Mensagem: `359139508681310212-535971522569961474`**

<hr>

{Sugestão} Criação de salas privadas automáticas.

**Comment by OswaldoDayJr** [comment]
Veja no discord a sugestão completa!.
