### ISSUE TITLE
Sugiro que removam esse sistema novo de rep da @Loritta Morenitta 😘, anti...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#374]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/336600728120590337/a_73a13298392e727345c36ae41723871c.gif">

**Sugestão de `FakeDGD#0001` (`336600728120590337`)**
**ID da Mensagem: `359139508681310212-543267833543524362`**

<hr>

Sugiro que removam esse sistema novo de rep da <@!297153970613387264>, antigamente era só digitar o comando e pronto, era mais simples, agora tem que entrar em um site e dizer porque você está dando reputação para fulano (Sem contar que isso é algo desnecessário já que pode ser ''burlado'' e você não precisa esclarecer um motivo para dar reputação para fulano). Sugiro que removam isso e deixem como antes.

PS: Sem contar que é meio bugado as vezes e o site pode estar offline.

**Comment by MrPowerGamerBR** [comment]
Não.

**Comment by 01Aleattrio01** [comment]
> Não.

Filho da putakkkkkkkk

**Comment by 01Aleattrio01** [comment]
> <img alt="" width="64" src="https://camo.githubusercontent.com/c647d2b38f3b7bc8b72d528320edd08a61de1ff4767d7f4ea35946279ab91dbe/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f617661746172732f3333363630303732383132303539303333372f615f37336131333239383339326537323733343563333661653431373233383731632e676966">
> 
> **Sugestão de `FakeDGD#0001` (`336600728120590337`)**
> **ID da Mensagem: `359139508681310212-543267833543524362`**
> 
> Sugiro que removam esse sistema novo de rep da <@!297153970613387264>, antigamente era só digitar o comando e pronto, era mais simples, agora tem que entrar em um site e dizer porque você está dando reputação para fulano (Sem contar que isso é algo desnecessário já que pode ser ''burlado'' e você não precisa esclarecer um motivo para dar reputação para fulano). Sugiro que removam isso e deixem como antes.
> 
> PS: Sem contar que é meio bugado as vezes e o site pode estar offline.

você está certo
sistema lixokkk
