### ISSUE TITLE
Comando +reroll pq se uma pessoa indesejável ganhou ou ela saiu ou outro m...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#379]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/514868327525646346/c998bc68bebb4a503170424dcf5da0cf.png">

**Sugestão de `greninja 2.0#3837` (`514868327525646346`)**
**ID da Mensagem: `359139508681310212-543574339534979074`**

<hr>

Comando +reroll pq se uma pessoa indesejável ganhou ou ela saiu ou outro motivo seria legal isso para os sorteios (giveaways)

**Comment by gui723668-star** [comment]
eu pode ser
