### ISSUE TITLE
Corrigir o bug do +remind list, que a reação de remover o lembrete some

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#385]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/351760430991147010/a_42dff73b7ce88af3acdd222c4ee6ddfb.gif">

**Sugestão de `Arth#4269` (`351760430991147010`)**
**ID da Mensagem: `359139508681310212-543798621674536960`**

<hr>

Corrigir o bug do `+remind list`, que a reação de remover o lembrete some

**Comment by MrPowerGamerBR** [comment]
Pelo visto a reação apenas "some" se você clicar rápido demais na reação antes da Lori terminar de enviar todas.
