### ISSUE TITLE
A Lori poderia bloquear convite discord.me também, ela não bloqueia

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#395]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/383742305968062479/4ff947825f8bce969ab17e21511774de.png">

**Sugestão de `Gabo 💫#0001` (`383742305968062479`)**
**ID da Mensagem: `359139508681310212-544242473590063114`**

<hr>

A Lori poderia bloquear convite discord.me também, ela não bloqueia

![https://cdn.discordapp.com/attachments/359139508681310212/544242468326211595/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/544242468326211595/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Ela não bloqueia porque eles mudaram como os invites são redirecionados.

Talvez será possível arrumar verificando a URL que está no `head` da página.
