### ISSUE TITLE
Hm, Seria Uma Boa, A Loritta Anti Vírus Amiga Do Anti Virus Do Windows 10,...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#412]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/537109977979158529/6de9afd2049c45674954e4abd85fc783.png">

**Sugestão de `OrFuck#9797` (`537109977979158529`)**
**ID da Mensagem: `359139508681310212-543944179945046070`**

<hr>

Hm, Seria Uma Boa, A Loritta Anti Vírus Amiga Do Anti Virus Do Windows 10, Naah To Zuando.

Bem, Poderia Ter No Painel, Na Opção De Divulgação, Algo Como **"Verificar Links Com Arquivos Maliciosos"** Ou Algo Assim, Quando Alguém Mandasse O Link, Ela Ia Excluir E Mandar Uma Mensagem, Tipo: Eii, Sem Pirataria Por Hoje <img src="https://cdn.discordapp.com/emojis/541309218893070348.png" width="16">, Seria Muito Bom Para Servidores Grandes Que Tenha Chats De Divulgação, Como O Do Cellbit Ou O Do Luba, É Meio Chato A Staff Ter Que Ficar verificando Esses links

~~se tu n entendeu, me chama no pv SIM EU SOU MT RUIM EM EXPLICAR ISSO~~

**Comment by MrPowerGamerBR** [comment]
Discord já tem isso (bem, na teoria tem)
