### ISSUE TITLE
criar o comando +gifmaker
ele funcionará assim

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#420]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/523916137562505227/81c1ffac905f93b2955142ddfc27af03.png">

**Sugestão de `Karinha Neko🐱#9264` (`523916137562505227`)**
**ID da Mensagem: `359139508681310212-545660413472276501`**

<hr>

criar o comando `+gifmaker`
ele funcionará assim: `+gifmaker <velocidade de quadros por segundo> <link dos quadros>`, em <velocidade de quadros por segundo> você coloca quantos quadros ou imagens vc quer que passe por segundo, e em <link dos quadros> você pega o links das imagens e cola, dai a loritta faz um gif com a imagem que você escolher

**Comment by Nightdavisao** [comment]
1. Isso não vai funcionar bem no Discord
2. Qual é a preguiça de abrir o navegador e procurar por um site de criar GIFs?
