### ISSUE TITLE
Adicionar mais tokens 

### ISSUE THREAD

**Issue by BlueSlimee** [LorittaBot/Loritta#45]
Adicionar mais tokens (Como `{guildsize}` e `{@user}`).

**Quais tokens?**
**•** - `{guild-icon-url}` - Retorna o URL do ícone da guild
**•** - `{lsl-url}` - Retorna a URL da página do servidor da Loritta Servers List (Se tiver vanity url, exibir ela)
**•** - `{promoted-count}` - Retorna quantas vezes um usuário já promoveu a guild do contexto.

**Progresso**

- [x] `{lsl-url}`

- [ ] `{promoted-count}`

- [x] `{guild-icon-url}`

**Comment by MrPowerGamerBR** [comment]
![https://mrpowergamerbr.com/uploads/DiscordCanary_2018-08-20_21-35-09.png](https://mrpowergamerbr.com/uploads/DiscordCanary_2018-08-20_21-35-09.png)
