### ISSUE TITLE
Criar um comando  +pat  para a Loritta, parecido com o +kiss e o +hug, só ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#453]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/335569045875195914/747e4972d15c6d56e69f3fe12344cb19.png">

**Sugestão de `||Arcën da Mïh||#9367` (`335569045875195914`)**
**ID da Mensagem: `359139508681310212-546799702159392779`**

<hr>

Criar um comando  ``+pat``  para a Loritta, parecido com o ``+kiss`` e o ``+hug``, só quer, obviamente, com um "pat".

**Comment by MrPowerGamerBR** [comment]
Feito
