### ISSUE TITLE
Não sei se é bug, mas, toda vez que você troca o nome nas configurações de...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#457]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/335569045875195914/747e4972d15c6d56e69f3fe12344cb19.png">

**Sugestão de `||Arcën da Mïh||#9367` (`335569045875195914`)**
**ID da Mensagem: `359139508681310212-547123383054237706`**

<hr>

Não sei se é bug, mas, toda vez que você troca o nome nas configurações de conta, a pontuação do ``+ship`` com outra pessoa é alterada. Seria legal corrigir?

**Comment by MrPowerGamerBR** [comment]
Isto é intencional, o valor do ship é baseado nos nomes dos dois usuários.
