### ISSUE TITLE
By:@Whiten#1046 Sistema de registro

### ISSUE THREAD

**Issue by Antipido** [LorittaBot/Loritta#46]
Acredito que seria uma ideia extremamente interessante se a Loritta tivese um sistema de mensagem privada (embed) para pessoas de um certo cargo, como por exemplo; Eu obtenho o cargo Gamer em meu servidor, então eu irei requisitar para que a Loritta mande uma mensagem para os demais membros dentro desse mesmo cargo, avisando que teremos um evento de Gamers, o comando poderia ser algo como [ +share @GAMER (mensagem) (cor da embed) ] , eu particularmente gostei muito e adoraria se essa opção fosse adicionada.
by:@Whiten#1046

**Comment by MrPowerGamerBR** [comment]
Duplicado #35
