### ISSUE TITLE
Sugiro um comando de "+headpet" com o alternativo de "+cafuné" que mostra ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#472]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/448537567831261197/e3e8f11877a400021b3b644853c40d66.png">

**Sugestão de `Vitamina Carlos#2694` (`448537567831261197`)**
**ID da Mensagem: `359139508681310212-548306669885587471`**

<hr>

Sugiro um comando de "+headpet" com o alternativo de "+cafuné" que mostra um gif aleatória de cafunés de animes, parecido com o +kiss, +hug, +slap e etc.

![https://cdn.discordapp.com/attachments/359139508681310212/548306664932245509/download.jpeg](https://cdn.discordapp.com/attachments/359139508681310212/548306664932245509/download.jpeg)

**Comment by MrPowerGamerBR** [comment]
Feito
