### ISSUE TITLE
Arrumar esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#485]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/526166974057807873/a39e9795df0e2cf41214c18341b0001c.png">

**Sugestão de `Hell#2648` (`526166974057807873`)**
**ID da Mensagem: `359139508681310212-548603265005387778`**

<hr>

Arrumar esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/548603260848701440/20190222_173342.jpg](https://cdn.discordapp.com/attachments/359139508681310212/548603260848701440/20190222_173342.jpg)

**Comment by VitorBlog** [comment]
WebHooks não conseguem mencionar usuários se eu não me engando

**Comment by MrGaabriel** [comment]
Intencional (para evitar com que as pessoas marquem @everyone e @here, além de irritar outros usuários)
