### ISSUE TITLE
Comando para ID do Emoji

### ISSUE THREAD

**Issue by Redig19** [LorittaBot/Loritta#51]
Poderia ter um comando que mostra-se o ID do Emoji que coloca-se, Exemplo:
"+emoji :lul:"

Loritta: ``ID Do Emoji``

**Comment by MarceloFIFA** [comment]
..emojiinfo

**Comment by mineiro123a** [comment]
+emojiinfo :pig-cry

**Comment by mineiro123a** [comment]
+emojiinfo 
![image](https://user-images.githubusercontent.com/87556479/126024503-7dda49a1-3f4a-4306-b167-66f33dd6f369.png)

**Comment by mineiro123a** [comment]
..emojiinfo 
![image](https://user-images.githubusercontent.com/87556479/126024513-c3c4d150-3c5e-4ad1-8a8f-73780d40970d.png)
