### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#511]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/180912328936521729/d5fe27b7c60d79f1985a97405f792828.png">

**Sugestão de `Dark_Pizza#3327` (`180912328936521729`)**
**ID da Mensagem: `359139508681310212-548707953616617492`**

<hr>

[BUG]

Quando a Loritta vai ler um código no +ocr ela não detecta os `{ }` e as vezes substitui por um `f`

![https://cdn.discordapp.com/attachments/359139508681310212/548707948592103424/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/548707948592103424/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Isso é um bug do OCR do Google.
