### ISSUE TITLE
Corrigir esse bug (que não reaje)

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#518]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/526166974057807873/a39e9795df0e2cf41214c18341b0001c.png">

**Sugestão de `Hell#2648` (`526166974057807873`)**
**ID da Mensagem: `359139508681310212-550112778044833792`**

<hr>

Corrigir esse bug (que não reaje)

![https://cdn.discordapp.com/attachments/359139508681310212/550112773523111976/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/550112773523111976/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
