### ISSUE TITLE
Corrigir bug de detecção de invites

### ISSUE THREAD

**Issue by BlueSlimee** [LorittaBot/Loritta#53]
**O que é esse bug?**
Se você enviar em um chat com o sistema de invite da lori um invite como `https://disCoRD.GG/servidor`, ela não detecta, e o Discord detecta como um servidor e exibe o embed.

**Comment by BlueSlimee** [comment]
Abafa, a Loritta está com um delay horrível no horário que a issue foi criada (23:47 GMT-4)

**Comment by MrGaabriel** [comment]
Já corrigido (#47)
