### ISSUE TITLE
Ter alguma opção no +searchemoji de "filtrar", se você quer uma imagem, ou...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#544]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/437612757852880906/660305081b0eefe143cc25d5727fa4ae.png">

**Sugestão de `Niibler#8348` (`437612757852880906`)**
**ID da Mensagem: `359139508681310212-551547032649597002`**

<hr>

Ter alguma opção no ``+searchemoji`` de "filtrar", se você quer uma imagem, ou um gif.

**Comment by Nightdavisao** [comment]
Você pode usar `+searchemoji <emoji> animated` se você quer apenas gifs

**Comment by MrPowerGamerBR** [comment]
Precisa colocar na ajuda do comando falando que é possível fazer isto.
