### ISSUE TITLE
No +userinfo mostrar se o usuário é nitro ou não e a casa da Hypesquad que...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#546]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/351760430991147010/6e44ad630fd42e01c6900251e4666867.png">

**Sugestão de `Arth#4269` (`351760430991147010`)**
**ID da Mensagem: `359139508681310212-551740196581015564`**

<hr>

No `+userinfo` mostrar se o usuário é nitro ou não e a casa da Hypesquad que ele pertence

**Comment by Nightdavisao** [comment]
Infelizmente isso não é possível devido às limitações da API do Discord, então apenas contas normais podem ver se um usuário é um assinante Nitro e etc
