### ISSUE TITLE
Quando você usa o +afk ou +falar e coloca um link de algum servidor, a Lor...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#551]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/350776956058599424/a_ef04fdf5e619e649489e8026fd432bcb.gif">

**Sugestão de `Filipe1234#0001` (`350776956058599424`)**
**ID da Mensagem: `359139508681310212-551503999287820310`**

<hr>

Quando você usa o +afk ou +falar e coloca um link de algum servidor, a Loritta não detecta (com o não poder divulgar convites habilitado). Acho que deveriam corrigir isso .-. <@!123170274651668480> `obs: ela não detecta quando o ser que está afk é mencionado`

![https://cdn.discordapp.com/attachments/359139508681310212/551503997853237259/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/551503997853237259/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Testado com o `+afk` e com o `+falor`, não funciona.
