### ISSUE TITLE
Corrigir esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#553]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/cf9c43c20eaa9265deb02c4202e43919.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-552272215983390721`**

<hr>

Corrigir esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/552272211080249344/Screenshot_2019-03-04-20-32-09.png](https://cdn.discordapp.com/attachments/359139508681310212/552272211080249344/Screenshot_2019-03-04-20-32-09.png)

**Comment by MrPowerGamerBR** [comment]
Isto foi corrigido quando o sistema de ações foi refeito.
