### ISSUE TITLE
Concertar esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#560]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/cf9c43c20eaa9265deb02c4202e43919.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-552560455135264808`**

<hr>

Concertar esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/552560452161372170/Screenshot_2019-03-05-15-37-36.png](https://cdn.discordapp.com/attachments/359139508681310212/552560452161372170/Screenshot_2019-03-05-15-37-36.png)

**Comment by MrPowerGamerBR** [comment]
Eu acho que já foi arrumado pois nunca mais reportaram este bug
