### ISSUE TITLE
Auto cargo por Reaction Message

### ISSUE THREAD

**Issue by StarlineBR** [LorittaBot/Loritta#60]
Gostaria que a Loritta tivesse um sistema de auto cargo por Reaction Message, igual do BOT (Reaction Role)
ID do BOT caso queira add no servidor por ID , pra verificar o funcionamento dele: 441751906428256277
![image](https://user-images.githubusercontent.com/31909648/45260202-e60f9200-b3b6-11e8-8f87-9db40313bc88.png)

**Comment by Alynva** [comment]
Essa sugestão foi abandonada?
