### ISSUE TITLE
Suporte pra live do Youtube gamming igual o BOT NOW LIVE...

### ISSUE THREAD

**Issue by StarlineBR** [LorittaBot/Loritta#62]
queria que o Loritta tivesse suporte de live no Youtube igual o BOT NOWLIVE que e compativel com live do Youtube gaming, mas quando a pessoa comeca live no YT normal e avisado sobre a live....

**Comment by MrGaabriel** [comment]
Bom... é suposto ela anunciar as livestreams quando elas começarem.

Mas se ela não anunciar, aí culpe o YouTube, pois ele é quem manda as notificações de vídeo para ela. Enfim, não há muito o que fazer...
