### ISSUE TITLE
Arrumar esse bug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#628]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/404313882757169153/8345a5df494aa4a2465d150485e41207.png">

**Sugestão de `󠀄󠀄󠀄󠀄󠀄󠀄Mafioso#0659` (`404313882757169153`)**
**ID da Mensagem: `359139508681310212-555135787839258626`**

<hr>

Arrumar esse bug

![https://cdn.discordapp.com/attachments/359139508681310212/555135787839258624/Screenshot_20190312_181101.jpg](https://cdn.discordapp.com/attachments/359139508681310212/555135787839258624/Screenshot_20190312_181101.jpg)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
