### ISSUE TITLE
Comando +genmc para gerar/entregar contas de minecraft em svs de rewards/l...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#631]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/523916137562505227/81c1ffac905f93b2955142ddfc27af03.png">

**Sugestão de `Karinha Neko🐱#9264` (`523916137562505227`)**
**ID da Mensagem: `359139508681310212-554484408787271690`**

<hr>

Comando `+genmc` para gerar/entregar contas de minecraft em svs de rewards/lojas
 • `+genmc stock`┋Irá mostrar quantas contas possuem no estoque do sv (Quantas alts, sfas e ufas)
 • `+genmc addstock <tipo> <conta no formato email:senha>`┋Precisa de permissão de gerenciar servidor para usar; Adiciona uma conta no estoque do servidor
Exemplo: `+genmc addstock ufa emailbolado@emailbolado.com:senhalegalzinha123` adiciona a conta emailbolado@emailbolado.com no estoque
 • `+genmc check <conta no formato email:senha> <Coloque toggleredirect se quiser que contas funcionais sejam add no stock>`┋Utiliza checkers para verificar se a conta é funcional ou não (Sobre a parte do redirect, se a conta checada for funcional, ela irá ser automaticamente adicionada ao stock. Caso o usuario não colocar nada alem da conta, a loritta irá apenas verificar a conta)
 • `+genmc generateacc <numero de contas> <link do gerador>`┋Permissão de gerenciar sv para utilizar; Utiliza um gerador(especificado no <link do gerador>) para criar contas de mine. Após o gerador criar as contas, informárá elas no chat, e um carimbo afrente das contas <formato email:senha> informando de que tipo ela é (Alt, sfa ou ufa)
 • `+genmc give <tipo>`┋Solicita uma conta de minecraft, a loritta irá enviar a conta no privado do usuário. (Para SFAs e UFAs, o usuario precisará convidar um certo numero de pessoas mo servidor para almentar a chance de cair uma sfa ou ufa. Alts terão 95% chance de cair, sfa 4% de chance e ufa 1% de chance)

**Comment by MrGaabriel** [comment]
A Loritta não incentiva pirataria + contas roubadas.
