### ISSUE TITLE
Corrigir este pequeno problema em que ela não está enviando as mensagens d...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#664]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/449940691045318656/dbfe9cb2d5cbaf9371c2a0fc7998caf7.png">

**Sugestão de `Foguinel#9864` (`449940691045318656`)**
**ID da Mensagem: `359139508681310212-557160994615328770`**

<hr>

Corrigir este pequeno problema em que ela não está enviando as mensagens da forma certa

![https://cdn.discordapp.com/attachments/359139508681310212/557160994615328768/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/557160994615328768/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido.
