### ISSUE TITLE
Lori n esta mostrando imagem com o {staff-avatar-url}

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#700]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/497539872676904990/9b6151f3cc032e327f5e6540ac849d75.png">

**Sugestão de `chell#4651` (`497539872676904990`)**
**ID da Mensagem: `359139508681310212-558131947079991320`**

<hr>

Lori n esta mostrando imagem com o {staff-avatar-url}

![https://cdn.discordapp.com/attachments/359139508681310212/558131942667583489/Screenshot_20190321-003050.png](https://cdn.discordapp.com/attachments/359139508681310212/558131942667583489/Screenshot_20190321-003050.png)

**Comment by MrPowerGamerBR** [comment]
Bug na hora de testar a mensagem, normalmente não dá problema
