### ISSUE TITLE
Não sei se vocês podem mas podia ter como abaixar este tempo de 6 segundos...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#701]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/431242673509367828/de4b835534a28560dd2cb68626d4324c.png">

**Sugestão de `! ๖̶̶̶ζ͜͡Apple 平和 🍎#0047` (`431242673509367828`)**
**ID da Mensagem: `359139508681310212-558722854175113317`**

<hr>

Não sei se vocês podem mas podia ter como abaixar este tempo de 6 segundos no painel da loritta

![https://cdn.discordapp.com/attachments/359139508681310212/558722849171308563/Screenshot_20190322-154408.png](https://cdn.discordapp.com/attachments/359139508681310212/558722849171308563/Screenshot_20190322-154408.png)

**Comment by MrPowerGamerBR** [comment]
Intencional, o cooldown é para proteger ela, e não você.
