### ISSUE TITLE
Corrigir esse bug do +renamechannel

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#703]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/523916137562505227/81c1ffac905f93b2955142ddfc27af03.png">

**Sugestão de `Karinha Neko🐱#9264` (`523916137562505227`)**
**ID da Mensagem: `359139508681310212-558734272408715275`**

<hr>

Corrigir esse bug do `+renamechannel`

![https://cdn.discordapp.com/attachments/359139508681310212/558734270848303125/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/558734270848303125/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Isso não é um bug, você que está usando o comando errado e colocando a culpa na Lori :woman_shrugging:
