### ISSUE TITLE
Sugestão - Comandos personalizados

### ISSUE THREAD

**Issue by XinXyla** [LorittaBot/Loritta#71]
Ter vários tipos de gatilhos para executar respostas e ações atravez de variáveis

### **Tipos de gatilhos:**
Prefixo
Começa com
Contém
Contém exatamente
Regex

### **REGEX**
`|` Separador
`(abc)` Qualquer palavra correspondida dentro de ()
`[abc]` Corresponde a qualquer unidade contida nos colchetes
`{abc}` Corresponde a qualquer coisa que não esteja entre as chaves

### **Exemplos de Regex:** 
(registrar|register|cadastrar)
[aeiou]{http} reposta: proibido conversar aqui, so pode postar imagens e links
{registrar|register|cadastrar} resposta: somente use as palavras chave

### **Variáveis**
`{user}` | Mostra o nome do usuário que provocou a ação
`{@user}` | Menciona o usuário que provocou a ação
`{user-created}` | Mostra a data e hora que o usuário criou a conta
`{user-joined}` | Mostra a data e hora que o usuário entrou no servidor
`{nickname}` | Mostra o nome do usuário no servidor (caso ele tenha mudado o apelido dele no servidor, irá aparecer o apelido dele, em vez do nome original)
`{user-discriminator}` | Mostra o discriminator do usuário que provocou a ação
`{user-id}` | Mostra o ID do usuário que provocou a ação
`{user-avatar-url}` | Mostra a URL do avatar do usuário
`{guild}` | Mostra o nome do servidor
`{guild-size}` | Mostra a quantidade de membros no servidor
`{guild-id}` | Mostra o ID do servidor
`{guild-icon}` | Mostra a URL da imagem do servidor
`{guild-created}` | Mostra a data e hora que o servidor foi criado
`{guild-region}` | Mostra a região do servidor
`{channel-id}` | Mostra a ID do canal atual que foi executado o comando
`{channel-name}` | Mostra o nome do canal atual que foi executado o comando
`{channel-mention}` | menciona o canal atual
`{time}` | Hora atual em PM/AM
`{time24}` | Hora atual
`{date}` | Data atual
`{hora}` | Hora atual em PM/AM no formato BR
`{hora24}` | Hora atual no formato BR
`{data}` | Data atual no formato BR
`{delete}` | Deleta o gatilho do comando
`{delete-response15}` | Deleta a resposta 15 segundos depois
`{delete-response30}` | Deleta a resposta 30 segundos depois
`{delete-response45}` | Deleta a resposta 45 segundos depois
`{delete-response60}` | Deleta a resposta 60 segundos depois
`{silent}` | Deleta o relatorio do comando
`$N` | Retorna um argumento, exemplos: ($1) ($4+) esse retorno funciona dentro de outros comandos como por exemplo `{+role $1 +<@&ID DO CARGO>}`
`{+comando}` | Executa comandos existentes na loritta ou cria fusão entre eles
`{require: <@&ID DO CARGO>}` | Requer um cargo para executar o comando
`{require:<#ID DO CANAL DE TEXTO>}` | Requer um canal de texto especifico para executar o comando
`{not:<@&ID DO CARGO>}` | Faz o comando não executar para quem possui o cargo (Para evitar conflitos este comando tem prioridade)
`{not:<#ID DO CANAL DE TEXTO>}` | Faz o comando não executar em determinado canal de texto (Para evitar conflitos este comando tem prioridade)
`{respond:<#ID DO CANAL DE TEXTO>}` | Envia a resposta para um canal de texto especifico
`{dm}` | Envia a resposta no PV
`{dm:<@ID DO USUARIO>}` | Envia a resposta no PV de outro usuario também usando o retorno de argumento, exemplo: {dm:$1}
`{+role {@user} +<@&ID DO CARGO>, +<@&ID DO CARGO>, ...}` | Adiciona o usuario em um ou mais cargos
`{+role {@user} -<@&ID DO CARGO>, -<@&ID DO CARGO>, ...}` | Remove o usuario de um ou mais cargos
`{+role {@user} -<@&ID DO CARGO>, +<@&ID DO CARGO>, ...}`
`{+rolename}` | Renomeia o cargo, exemplo: {+rolename <@&ID DO CARGO>, $1+ }
`{+rolecolor}` | Altera a cor do cargo, exemplo {+rolecolor <@&ID DO CARGO>, $1+ }
`{+delrole}` | Exclui um cargo
`{+addrole}` | Cria um cargo
`{+mentionrole}` | Alterna para mencionar ou não o cargo
`{vote-count}` | Mostra quantos votos o usuário que votou possui
`{lsl-url}` | Mostra a url para votar no servidor
`{reaction:}` | Adiciona uma reação na mensagem de gatilho
`{reaction-response:}` | Adiciona uma ou mais reações na mensagem de resposta, exemplo {reaction-response:pandinha;koala;👍;👎}
`{reaction-role}` | Adiciona/Remove um ou mais cargos usando uma reação especifica, exemplo {reaction-role :koalinha: +<@&ID DO CARGO>, -<@&ID DO CARGO>}
`{embed}` | Transforma a resposta em embed - MrPowerGamerBR eu não sei como isso funcionaria então vou dar um exemplo tosco que poderia ser simples de montar, pelo menos eu acho...

{embed:
(content: conteudo)
(color: conteudo)
(name: exemplo {@user})
(title: conteudo)
(description: conteudo)
(author-name: conteudo)
(author-icon_url: exemplo {user-avatar-url})
(image-url: exemplo $1)
(thumbnail-url: exemplo {user-avatar-url}")
(footer-icon_url: conteudo)
(footer-text: exemplo {user-id} | {data} - {hora})
}

### **Opções de Cooldown**
cooldown padrão da loritta
cooldown do usuário
cooldown do servidor

![comandos personalizados](https://user-images.githubusercontent.com/43226244/45467667-2c3a5d80-b6f7-11e8-92d5-b0c5da58f4b7.png)

**Comment by XinXyla** [comment]
> Ter vários tipos de gatilhos para executar respostas e ações atravez de variáveis
> 
> ### **Tipos de gatilhos:**
> Prefixo
> Começa com
> Contém
> Contém exatamente
> Regex
> 
> ### **REGEX**
> `|` Separador
> `(abc)` Qualquer palavra correspondida dentro de ()
> `[abc]` Corresponde a qualquer unidade contida nos colchetes
> `{abc}` Corresponde a qualquer coisa que não esteja entre as chaves
> 
> ### **Exemplos de Regex:**
> (registrar|register|cadastrar)
> [aeiou]{http} reposta: proibido conversar aqui, so pode postar imagens e links
> {registrar|register|cadastrar} resposta: somente use as palavras chave
> 
> ### **Variáveis**
> `{user}` | Mostra o nome do usuário que provocou a ação
> `{@user}` | Menciona o usuário que provocou a ação
> `{user-created}` | Mostra a data e hora que o usuário criou a conta
> `{user-joined}` | Mostra a data e hora que o usuário entrou no servidor
> `{nickname}` | Mostra o nome do usuário no servidor (caso ele tenha mudado o apelido dele no servidor, irá aparecer o apelido dele, em vez do nome original)
> `{user-discriminator}` | Mostra o discriminator do usuário que provocou a ação
> `{user-id}` | Mostra o ID do usuário que provocou a ação
> `{user-avatar-url}` | Mostra a URL do avatar do usuário
> `{guild}` | Mostra o nome do servidor
> `{guild-size}` | Mostra a quantidade de membros no servidor
> `{guild-id}` | Mostra o ID do servidor
> `{guild-icon}` | Mostra a URL da imagem do servidor
> `{guild-created}` | Mostra a data e hora que o servidor foi criado
> `{guild-region}` | Mostra a região do servidor
> `{channel-id}` | Mostra a ID do canal atual que foi executado o comando
> `{channel-name}` | Mostra o nome do canal atual que foi executado o comando
> `{channel-mention}` | menciona o canal atual
> `{time}` | Hora atual em PM/AM
> `{time24}` | Hora atual
> `{date}` | Data atual
> `{hora}` | Hora atual em PM/AM no formato BR
> `{hora24}` | Hora atual no formato BR
> `{data}` | Data atual no formato BR
> `{delete}` | Deleta o gatilho do comando
> `{silent}` | Deleta o relatorio do comando
> `$N` | Retorna um argumento, exemplos: ($1) ($4+) esse retorno funciona dentro de outros comandos como por exemplo `{+role $1 +<@&ID DO CARGO>}`
> `{+comando}` | Executa comandos existentes na loritta ou cria fusão entre eles
> `{require: <@&ID DO CARGO>}` | Requer um cargo para executar o comando
> `{require:<#ID DO CANAL DE TEXTO>}` | Requer um canal de texto especifico para executar o comando
> `{not:<@&ID DO CARGO>}` | Faz o comando não executar para quem possui o cargo (Para evitar conflitos este comando tem prioridade)
> `{not:<#ID DO CANAL DE TEXTO>}` | Faz o comando não executar em determinado canal de texto (Para evitar conflitos este comando tem prioridade)
> `{respond:<#ID DO CANAL DE TEXTO>}` | Envia a resposta para um canal de texto especifico
> `{dm}` | Envia a resposta no PV
> `{dm:<@ID DO USUARIO>}` | Envia a resposta no PV de outro usuario também usando o retorno de argumento, exemplo: {dm:$1}
> `{+role {@user} +<@&ID DO CARGO>, +<@&ID DO CARGO>, ...}` | Adiciona o usuario em um ou mais cargos
> `{+role {@user} -<@&ID DO CARGO>, -<@&ID DO CARGO>, ...}` | Remove o usuario de um ou mais cargos
> `{+role {@user} -<@&ID DO CARGO>, +<@&ID DO CARGO>, ...}`
> `{+rolename}` | Renomeia o cargo, exemplo: {+rolename <@&ID DO CARGO>, $1+ }
> `{+rolecolor}` | Altera a cor do cargo, exemplo {+rolecolor <@&ID DO CARGO>, $1+ }
> `{+delrole}` | Exclui um cargo
> `{+addrole}` | Cria um cargo
> `{+mentionrole}` | Alterna para mencionar ou não o cargo
> `{vote-count}` | Mostra quantos votos o usuário que votou possui
> `{embed}` | Transforma a resposta em embed - MrPowerGamerBR eu não sei como isso funcionaria então vou dar um exemplo tosco que poderia ser simples de montar, pelo menos eu acho...
> 
> {embed:
> (content: conteudo)
> (color: conteudo)
> (name: exemplo {@user})
> (title: conteudo)
> (description: conteudo)
> (author-name: conteudo)
> (author-icon_url: exemplo {user-avatar-url})
> (image-url: exemplo $1)
> (thumbnail-url: exemplo {user-avatar-url}")
> (footer-icon_url: conteudo)
> (footer-text: exemplo {user-id} | {data} - {hora})
> }
> 
> ### **Opções de Cooldown**
> cooldown padrão da loritta
> cooldown do usuário
> cooldown do servidor
> 
> ![comandos personalizados](https://user-images.githubusercontent.com/43226244/45467667-2c3a5d80-b6f7-11e8-92d5-b0c5da58f4b7.png)

**Comment by XinXyla** [comment]
Ah esqueci de mencionar, seria melhor deixar tudo em resposta pois as vezes eu salvo a página inteira com os codigos todos, assim caso tudo seja perdido é possivel recuperar de forma rapida e facil além de ser facil migrar os codigos para outro servidor

**Comment by BlueSlimee** [comment]
Se o `{hora}` for o horário no Brasil, pode acabar dando problema porque o Brasil tem mais de 1 fuso horário, então, acho que seria mais interessante um `{horaGMT("+3")}` e `{horaUTC("+2")}`.

**Comment by MrPowerGamerBR** [comment]
Isto na verdade é mais um "respostas automáticas" + "comandos personalizados de uma maneira mais fácil", né?

**Comment by MrGaabriel** [comment]
> Isto na verdade é mais um "respostas automáticas" + "comandos personalizados de uma maneira mais fácil", né?

Acredito que sim
