### ISSUE TITLE
Aqui tem sugestões mas não significa que tem que ser só de comandos eu rec...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#719]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/431242673509367828/de4b835534a28560dd2cb68626d4324c.png">

**Sugestão de `! ๖̶̶̶ζ͜͡Apple 平和 🍎#0047` (`431242673509367828`)**
**ID da Mensagem: `359139508681310212-559395414571221016`**

<hr>

**Aqui tem sugestões mas não significa que tem que ser só de comandos eu recomendo uma foto pro +kiss que é a foto abaixo**

![https://cdn.discordapp.com/attachments/359139508681310212/559395413627633664/tumblr_n3uuspnYB11r0fg96o1_500.gif](https://cdn.discordapp.com/attachments/359139508681310212/559395413627633664/tumblr_n3uuspnYB11r0fg96o1_500.gif)

**Comment by MrPowerGamerBR** [comment]
Feito
