### ISSUE TITLE
(Sugestão) A Loritta poder executar musica em mais de um canal ao mesmo tempo

### ISSUE THREAD

**Issue by MarcosHgames** [LorittaBot/Loritta#72]
Se a Loritta pode-se passar musica em mais de um canal ao mesmo tempo ex.
http://prntscr.com/kusk1l

Seria bem útil para quem gosta de tipos diferentes é não precisaria escutar oque não gosta

**Comment by bolsomito** [comment]
Eu tenho a certeza que isso é impossível de fazer, sendo que bots não podem fazer isso.
