### ISSUE TITLE
Não é exatamente uma sugestão, é um erro que acontece na Loritta, que ao i...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#728]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/373547733975433216/e89f3e7c225f226f8660783d64e4f9a4.png">

**Sugestão de `EJ palhaso (desafio aa)#7482` (`373547733975433216`)**
**ID da Mensagem: `359139508681310212-559522615488806922`**

<hr>

Não é exatamente uma sugestão, é um erro que acontece na Loritta, que ao invés de ela falar "Renomear", ela fala "Renomar".

![https://cdn.discordapp.com/attachments/359139508681310212/559522612024311818/erro-loritta.png](https://cdn.discordapp.com/attachments/359139508681310212/559522612024311818/erro-loritta.png)

**Comment by MrPowerGamerBR** [comment]
Já foi corrigido
