### ISSUE TITLE
Comando poke ou cutucar (não consegui colocar o GIF, mas como exemplo, um ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#760]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/470336604326592512/e42a945314e626a6b34346b860d72385.png">

**Sugestão de `Caramela#8156` (`470336604326592512`)**
**ID da Mensagem: `359139508681310212-561243201134919706`**

<hr>

Comando `poke` ou `cutucar` (não consegui colocar o GIF, mas como exemplo, um print desse GIF)

![https://cdn.discordapp.com/attachments/359139508681310212/561243193954533377/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/561243193954533377/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Para fazer esse, precisa de mais GIFs
