### ISSUE TITLE
Tenho uma sugestão

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#775]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/422839753923362827/9eebe6e98b571faf3ece3c51fd48f63f.png">

**Sugestão de `☕ Ink!Sans [CL] 🍪#7084` (`422839753923362827`)**
**ID da Mensagem: `359139508681310212-561914844014706709`**

<hr>

**Tenho uma sugestão: **

**Eu acho que seria bom criar um módulo para a Loritta de LEVEL... Atualmente eu uso o MEE6 como BOT pra level, mas pode ter certeza que se tivesse esse módulo para a Loritta eu usaria com certeza, aliás meu server é de Undertale e eu preciso desse módulo para mostrar o tanto de L.O.V.E ou Amor que o membro está :3 Espero que veja minha sugestão e pensem nela ;w; Obrigada 💛 **

```Exemplo do que eu uso com o MEE6:```

![https://cdn.discordapp.com/attachments/359139508681310212/561914838045949992/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/561914838045949992/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
