### ISSUE TITLE
Vocês pensam em possibilitar um sistema igual ao do MEE6, onde quando você...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#797]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/251742365826547712/a_33fcc209066ba557be34244a282c80ce.gif">

**Sugestão de `Natural#0001` (`251742365826547712`)**
**ID da Mensagem: `359139508681310212-563452915994329110`**

<hr>

Vocês pensam em possibilitar um sistema igual ao do MEE6, onde quando você alcança uma certa quantia de XP/Level no server o bot te dá o cargo do respectivo level?

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
