### ISSUE TITLE
Ultilizando as velhas ``

### ISSUE THREAD

**Issue by Craftzao** [LorittaBot/Loritta#8]
Como proteção para não ultilizarem everyone a Loritta tira as `` dos argumentos do usuario que executou o comando antes de executa-lo
Então se o usuario ultilizar +serverinfo `` por exemplo, ou em qualquer comando que precise de um argumento para funcionar, ela vai dar um erro

**Comment by MrPowerGamerBR** [comment]
https://github.com/LorittaBot/Loritta/blob/master/src/main/java/com/mrpowergamerbr/loritta/commands/CommandBase.kt#L239
