### ISSUE TITLE
{BUG} +vemdezap

### ISSUE THREAD

**Issue by OswaldoDayJr** [LorittaBot/Loritta#82]
Erro no comando "+vemdezap" quando usamos o comando a Lori retorna como se nós não usou nem um argumento mesmo que o comando não tenha aguento. Ué como asim não entendi.

Veja no Discord: https://discordapp.com/channels/297732013006389252/359139508681310212/497883983065907240

**Comment by MrGaabriel** [comment]
Mande uma screenshot

**Comment by OswaldoDayJr** [comment]
@MrGaabriel 
![screenshot_20181028-115849](https://user-images.githubusercontent.com/40673064/47617755-4367bb80-daa9-11e8-9db6-1735dba5d538.png)

**Comment by MrGaabriel** [comment]
Então é no exemplo de "como usar"?

**Comment by OswaldoDayJr** [comment]
@MrGaabriel Porém o comando não tem argumentos para usar

**Comment by MrGaabriel** [comment]
Aqui está funcionando corretamente.

![screenshot](https://mrgaabriel.space/files/DiscordCanary_2018-10-28-12-04-14.png)

**Comment by MrPowerGamerBR** [comment]
O problema que ele está falando é que está faltando o `Como usar`

**Comment by MrGaabriel** [comment]
Ah, entendi

**Comment by MrPowerGamerBR** [comment]
Corrigido na Canary

![https://i.imgur.com/WhRQY4A.png](https://i.imgur.com/WhRQY4A.png)
