### ISSUE TITLE
Bug no +mcavatar

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#822]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/529766889417605125/ac30f54fa2b9d81ce3460d4ae0815be8.png">

**Sugestão de `ℳℛ. ᏉⅈℂͲ❆ℛ#6174` (`529766889417605125`)**
**ID da Mensagem: `359139508681310212-564190375670054942`**

<hr>

Bug no +mcavatar

![https://cdn.discordapp.com/attachments/359139508681310212/564190368023838854/Screenshot_2019-04-06-17-50-31.png](https://cdn.discordapp.com/attachments/359139508681310212/564190368023838854/Screenshot_2019-04-06-17-50-31.png)

**Comment by MrPowerGamerBR** [comment]
Isso era bug na API da Mojang, e não na Loritta
