### ISSUE TITLE
Pessoas com cargos especiais aqui (Como donators, desenhistas) ganharem um...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#823]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/2ca574257caf14ccbc1a6504098a3dcf.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-564434004632403979`**

<hr>

Pessoas com cargos especiais aqui (Como donators, desenhistas) ganharem um boost nos seus sonhos

**Comment by BlueSlimee** [comment]
Relacionado ao Apartamento da Loritta.
