### ISSUE TITLE
a Loritta poderia regair ❓ para pessoas que não entenderam as sugestões do...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#833]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/48cc7d1413d762f28888c8e585e26501.png">

**Sugestão de `LynaX_X#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-564519633311367171`**

<hr>

a Loritta poderia regair ❓ para pessoas que não entenderam as sugestões dos outros ;-; As vezes tem pessoas q não entendem as sugestões e não tem a reação ❓ para dúvida ou desentendimento ;_;

**Comment by BlueSlimee** [comment]
Se você não consegue explicar o que quer sugerir, acho que isso também não irá ajudar. Irei fechar a issue até recebermos mais informações/opiniões sobre essa funcionalidade.
