### ISSUE TITLE
Uma auto-verificação dos membros novos... você define um canal para enviar...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#837]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/540976244221673473/8a3d2559739716291ca16fd3a7b8290a.png">

**Sugestão de `zP996xDalhy__#4278` (`540976244221673473`)**
**ID da Mensagem: `359139508681310212-563790000399843328`**

<hr>

Uma auto-verificação dos membros novos... você define um canal para enviar informações de players novos que entrarem!

**Comment by BlueSlimee** [comment]
É mais simples adicionar novos placeholders.
