### ISSUE TITLE
Corrigir esse  "possivel Bug", que quando o nome de um canal é alterado ap...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#841]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/373566104615911427/606d84237943be45a7b0a4e4b24d7509.png">

**Sugestão de `TnTuzumaki666#6527` (`373566104615911427`)**
**ID da Mensagem: `359139508681310212-563866453984411648`**

<hr>

Corrigir esse  "possivel Bug", que quando o nome de um canal é alterado aparece esse "null" e os " `` ", coisa que também acontece quando coloca mais que um espaço quando vai usar o "+pay"

![https://cdn.discordapp.com/attachments/359139508681310212/563866446753562624/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/563866446753562624/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Esses audit logs foram removidos, então...
