### ISSUE TITLE
+retroceder e +avançar para retroceder/avançar segundos em uma música na D...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#844]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/416056545051279370/69707c0ef268f9b80bbcaaf3f09f2405.png">

**Sugestão de `Dokyo ✨#2569` (`416056545051279370`)**
**ID da Mensagem: `359139508681310212-565341184981991434`**

<hr>

`+retroceder` e `+avançar` para retroceder/avançar segundos em uma música na DJ Loritta

**Comment by BlueSlimee** [comment]
O +seek tem uma funcionalidade parecida.
