### ISSUE TITLE
o mute da Loritta poderia ser + rápido. Ela pede os dias, horas, meses pra...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#847]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/48cc7d1413d762f28888c8e585e26501.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-565632088733122616`**

<hr>

o mute da Loritta poderia ser + rápido. Ela pede os dias, horas, meses pra mutar a pessoa no chat... 
EX:
+mute {@user} {minutos, horas, dias, meses, datas, anos...} {motivo} (se quiserem podem ignorar o motivo)

**Comment by BlueSlimee** [comment]
Não pede não.
