### ISSUE TITLE
Corrigir um BUG onde não mostra o nome do Streamer cadastrado/registrado n...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#850]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/286157492621279232/5f4cd4fbdc33b0b1cdaeea43ce3a8281.png">

**Sugestão de `crashzk#9695` (`286157492621279232`)**
**ID da Mensagem: `359139508681310212-565395725173653504`**

<hr>

Corrigir um BUG onde não mostra o nome do Streamer cadastrado/registrado no Painel de Loritta quando envia a mensagem.

***Obs: Quando faz o teste com a mensagem ele mostra o nome do streamer normalmente.***

![https://cdn.discordapp.com/attachments/359139508681310212/565395716789370905/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/565395716789370905/unknown.png)

**Comment by MrPowerGamerBR** [comment]
Duplicata de https://github.com/LorittaBot/Loritta/issues/912
