### ISSUE TITLE
O comando +ligar podia servir para mais alguma coisa, podia ter como a lor...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#855]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/448999125120188416/a_1ab9caeed4d25062c864cfb542380d79.gif">

**Sugestão de `Luiggy007#0007` (`448999125120188416`)**
**ID da Mensagem: `359139508681310212-565758418363744257`**

<hr>

O comando +ligar podia servir para mais alguma coisa, podia ter como a loritta fazer uma chamada para seu selular e falar qualquer coisa como "Oi! Você ligou?" .

**Comment by BlueSlimee** [comment]
Complexo e causaria diversos problemas.

**Comment by PurpleVibe32** [comment]
Imagine os trotes..
