### ISSUE TITLE
colocar um comando +fanart para aparecer uma fanart aleatória feita pela g...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#857]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/372470709961621520/5c1d6800809a8ca33eb46bde4524acac.png">

**Sugestão de `✨Mandy ✨#4535` (`372470709961621520`)**
**ID da Mensagem: `359139508681310212-566075041595392013`**

<hr>

colocar um comando +fanart para aparecer uma fanart aleatória feita pela galera <img src="https://cdn.discordapp.com/emojis/542686098841796609.png" width="16">

**Comment by BlueSlimee** [comment]
Esse comando já existe. Use `+fanarts`.
