### ISSUE TITLE
A Loritta poderia um comando chamado +mobile Esse comando iria indicar se ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#862]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/475651109978112022/48cc7d1413d762f28888c8e585e26501.png">

**Sugestão de `Lyna#1544` (`475651109978112022`)**
**ID da Mensagem: `359139508681310212-566006428939190282`**

<hr>

A Loritta poderia um comando chamado ``+mobile`` Esse comando iria indicar se a pessoa está pelo celular

**Comment by BlueSlimee** [comment]
Apenas contas de usuários podem ter acesso a esses tipos de informações.
