### ISSUE TITLE
+morder @pessoa

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#863]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/533330738649759745/0fee09ee938740c48387a8e07dc0bce8.png">

**Sugestão de `RafaGotico#8924` (`533330738649759745`)**
**ID da Mensagem: `359139508681310212-565614638620737547`**

<hr>

`+morder @pessoa`

**Comment by MrPowerGamerBR** [comment]
Precisa de GIFs para eu fazer isto
