### ISSUE TITLE
Ter função de levels igual o mee6 tinha, que funciona com xp.

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#869]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/330030557457022986/85def1e6775b1562c6c48aa67da25e50.png">

**Sugestão de `žэяэƒ-sαмα#0474` (`330030557457022986`)**
**ID da Mensagem: `359139508681310212-566428447279284231`**

<hr>

Ter função de levels igual o mee6 tinha, que funciona com xp.

**Comment by MrPowerGamerBR** [comment]
Implementado em https://github.com/LorittaBot/Loritta/commit/a2428b5226005cd16fa72ba9f6223cf485939dc4
