### ISSUE TITLE
Colocar esse gif para o +kiss

https

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#880]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/361977144445763585/b92ea758677bf292954812cf05fe45c0.png">

**Sugestão de `PeterStark000#6011` (`361977144445763585`)**
**ID da Mensagem: `359139508681310212-567047557684133900`**

<hr>

Colocar esse gif para o ``+kiss``

`https://media1.tenor.com/images/ea51c3a083c73bf81a3c5ee6d4165115/tenor.gif?itemid=11794176`

**Comment by MrPowerGamerBR** [comment]
Adicionado! ^-^
