### ISSUE TITLE
+spotify - Mostra as informações da música que você está escutando atualmente

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#884]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/2ca574257caf14ccbc1a6504098a3dcf.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-567088084659732490`**

<hr>

`+spotify` - Mostra as informações da música que você está escutando atualmente

**Comment by BlueSlimee** [comment]
Não vejo necessidade de tal função. Mobile e PC conseguem ver o Tocando do Spotify, tornando essa função inútil.
