### ISSUE TITLE
Vender bonecos da Lori como em porta chaves ?

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#886]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/477849121013891073/dc0a884415ce34a6215743ceda88c8c7.png">

**Sugestão de `яαfαєℓ💚#8736` (`477849121013891073`)**
**ID da Mensagem: `359139508681310212-567141769662169098`**

<hr>

Vender bonecos da Lori como em porta chaves ?

**Comment by BlueSlimee** [comment]
???
