### ISSUE TITLE
Colocar esse GIF pro +hug

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#902]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/519477864576581642/0bad059a4f3d4d2d5e169bd1dee4b8fa.png">

**Sugestão de `🐉🌹Jedson💃🍃#7523` (`519477864576581642`)**
**ID da Mensagem: `359139508681310212-568559613059006467`**

<hr>

Colocar esse GIF pro `+hug`

![https://cdn.discordapp.com/attachments/359139508681310212/568559606289137664/tenor.gif](https://cdn.discordapp.com/attachments/359139508681310212/568559606289137664/tenor.gif)

**Comment by MrPowerGamerBR** [comment]
Adicionado ^-^
