### ISSUE TITLE
Retirar o timer do #🤷│dúvidas＆suporte, muita das vezes ninguém olha o can...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#903]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/2ca574257caf14ccbc1a6504098a3dcf.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-567847012150542376`**

<hr>

Retirar o timer do `#🤷│dúvidas＆suporte` (`398987569485971466`), muita das vezes ninguém olha o canal pensando que é a notificação do timer

**Comment by BlueSlimee** [comment]
Relacionado ao Apartamento da Loritta.
