### ISSUE TITLE
Ser possível ver informações de um canal de voz no +channelinfo.

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#906]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/395788326835322882/660c3fd82d7d1467f907fce4559b1562.png">

**Sugestão de `DanielaGC_#4318` (`395788326835322882`)**
**ID da Mensagem: `359139508681310212-568645222246907914`**

<hr>

Ser possível ver informações de um canal de voz no `+channelinfo`.

**Comment by BlueSlimee** [comment]
@Nightdavisao
