### ISSUE TITLE
+stop - Simula uma partida de stop no chat

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#907]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/466650671492366374/2ca574257caf14ccbc1a6504098a3dcf.png">

**Sugestão de `Yuri#9178` (`466650671492366374`)**
**ID da Mensagem: `359139508681310212-568572495712616469`**

<hr>

`+stop` - Simula uma partida de stop no chat

**Comment by BlueSlimee** [comment]
`+stop` é de música, precisa de outro nome.
