### ISSUE TITLE
Nesse chat poderia ser possível usar > pra Lori não reagir, assim podendo ...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#910]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/383742305968062479/b773c56f30c9b6c68adf9e2a1d9d3d1a.png">

**Sugestão de `Gabo#6235` (`383742305968062479`)**
**ID da Mensagem: `359139508681310212-568452794814824490`**

<hr>

Nesse chat poderia ser possível usar > pra Lori não reagir, assim podendo responder caso alguma sugestão já exista

**Comment by BlueSlimee** [comment]
Relacionado ao Apartamento da Loritta.
