### ISSUE TITLE
minha sugestão é mais pra uma dica de fazer com que o site da loritta tive...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#911]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/419490832664625162/5c112e7aba0e3d6b0f66e214099cf2b0.png">

**Sugestão de `Coffy#8137` (`419490832664625162`)**
**ID da Mensagem: `359139508681310212-568651858466308097`**

<hr>

minha sugestão é mais pra uma dica de fazer com que o site da loritta tivesse a opção de colocar tema escuro, essa é a coisa mais útil de todo o planeta desde que os sites e navegadores incluindo apps colocaram essa opção de tema escuro ou claro, agrada muito olhos frágeis

**Comment by BlueSlimee** [comment]
O site já tem...
