### ISSUE TITLE
bugzinho na {streamer}

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#912]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/235075700262961152/309f624152db40c2c906ec09af1f5e4a.png">

**Sugestão de `NearKing#9089` (`235075700262961152`)**
**ID da Mensagem: `359139508681310212-568595367554318340`**

<hr>

bugzinho na {streamer}

![https://cdn.discordapp.com/attachments/359139508681310212/568595365859950603/Screenshot_20190418-212358.png](https://cdn.discordapp.com/attachments/359139508681310212/568595365859950603/Screenshot_20190418-212358.png)

**Comment by MrPowerGamerBR** [comment]
Intencional, mas deveria remover o placeholder do painel.
