### ISSUE TITLE
Sugiro uma adição aos usuários de mobile um comando do tipo +recolor <role...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#913]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/409860394535092255/14249f610e93843ec1d650cdfb82ba46.png">

**Sugestão de `Tigrin#7900` (`409860394535092255`)**
**ID da Mensagem: `359139508681310212-568717431934025740`**

<hr>

Sugiro uma adição aos usuários de mobile um comando do tipo **+recolor <role mention> <Hex code color> **

**Comment by BlueSlimee** [comment]
O que esse comando faz?
