### ISSUE TITLE
arruma esses bug aew https

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#917]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/511946504257142785/1237b2ebd46292077f23ca13043cc461.png">

**Sugestão de `ZXbatata123#3128` (`511946504257142785`)**
**ID da Mensagem: `359139508681310212-568936408316641280`**

<hr>

arruma esses bug aew ![https://cdn.discordapp.com/attachments/398987569485971466/568935325989077003/unknown.png](https://cdn.discordapp.com/attachments/398987569485971466/568935325989077003/unknown.png) ![https://cdn.discordapp.com/attachments/398987569485971466/568936002215739418/unknown.png](https://cdn.discordapp.com/attachments/398987569485971466/568936002215739418/unknown.png)

**Comment by BlueSlimee** [comment]
Como acontece o bug na primeira imagem? O na 2ª imagem é um problema com o JDA, não podemos fazer nada.
