### ISSUE TITLE
Mais comandos bugados depois de ela ter reiniciados as shards ontem a noite!

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#922]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/552501138990039040/2ba24d5141fcaf3eb23101ca4845f789.png">

**Sugestão de `JSSP#3830` (`552501138990039040`)**
**ID da Mensagem: `359139508681310212-569463214300200980`**

<hr>

Mais comandos bugados depois de ela ter reiniciados as shards ontem a noite!

![https://cdn.discordapp.com/attachments/359139508681310212/569463208050556928/Screenshot_20190421-070308.png](https://cdn.discordapp.com/attachments/359139508681310212/569463208050556928/Screenshot_20190421-070308.png)

**Comment by MrPowerGamerBR** [comment]
Tinha acabado o espaço no container dela, isso já foi corrigido.
