### ISSUE TITLE
traduzir isso corretamente

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#923]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/284982304848478209/879cec32a6fc07c9e8c8f444766b3509.png">

**Sugestão de `Masamoto#6914` (`284982304848478209`)**
**ID da Mensagem: `359139508681310212-569592318856921108`**

<hr>

traduzir isso corretamente

![https://cdn.discordapp.com/attachments/359139508681310212/569592311810621442/sad_reality.png](https://cdn.discordapp.com/attachments/359139508681310212/569592311810621442/sad_reality.png)

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/LorittaLocales/commit/f507380ac4fce3e3314308d2a69e6bd09fe22d9a
