### ISSUE TITLE
É preciso 7500 sonhos para se casar, mas quando você faz uma proposta para...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#949]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/317796741024055307/81561fc709b83fed43539addf68dffa1.png">

**Sugestão de `Lion#6221` (`317796741024055307`)**
**ID da Mensagem: `359139508681310212-571049267746177025`**

<hr>

É preciso 7500 sonhos para se casar, mas quando você faz uma proposta para alguém, fica descrito que custa 10000 sonhos...

![https://cdn.discordapp.com/attachments/359139508681310212/571049258162061312/unknown.png](https://cdn.discordapp.com/attachments/359139508681310212/571049258162061312/unknown.png)

**Comment by emilly-bit** [comment]
Uau
