### ISSUE TITLE
A Lori mudou ne? No comando  +akinator  Sinto falta do botão "voltar" quan...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#966]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/443193314368552979/ec427214cfa31d433efeca03186825fc.png">

**Sugestão de `ChokoYasmin#3619` (`443193314368552979`)**
**ID da Mensagem: `359139508681310212-571522492410363904`**

<hr>

A Lori mudou ne? No comando `` +akinator `` Sinto falta do botão "voltar" quando sem querer marcamos errado, poderia colocar de volta?

**Comment by MrPowerGamerBR** [comment]
Eu tinha tentado implementar isto, mas a library que eu estou usando (Akiwrapper) para estar com problemas ao tentar fazer que a pergunta "volte"

Mas é algo que precisa ser implementado porque é bastante útil
