### ISSUE TITLE
Resolver este bug com o +play da Loritta...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#972]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/473568995434299423/c4a96ff3f780ba5190a27bb0f676ff07.png">

**Sugestão de `desumat#9090` (`473568995434299423`)**
**ID da Mensagem: `359139508681310212-571672362056024064`**

<hr>

**Resolver este bug com o `+play` da Loritta...**

![https://cdn.discordapp.com/attachments/359139508681310212/571672351976980481/Screenshot_38.png](https://cdn.discordapp.com/attachments/359139508681310212/571672351976980481/Screenshot_38.png)

**Comment by MrPowerGamerBR** [comment]
Sistema de música foi desativado
