### ISSUE TITLE
Arrumar bug em que fixar uma mensagem faz com que a lori rode o comando de...

### ISSUE THREAD

**Issue by LorittaMorenitta** [LorittaBot/Loritta#983]
<img width="64" align="left" src="https://cdn.discordapp.com/avatars/485837271967465472/e18b2406aa54298854a839bef11834dc.png">

**Sugestão de `Blue Slime#2555` (`485837271967465472`)**
**ID da Mensagem: `359139508681310212-572581422200651806`**

<hr>

Arrumar bug em que fixar uma mensagem faz com que a lori rode o comando de novo

**Comment by MrPowerGamerBR** [comment]
É meio que impossível arrumar esse bug já que "mensagem fixada" é contado como um update, e não tem jeito de saber se a mensagem foi fixada ou não.
